-- Create daily_check_ins table
CREATE TABLE IF NOT EXISTS daily_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    check_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    reward_amount INTEGER DEFAULT 10,
    CONSTRAINT unique_daily_check_in UNIQUE (user_id, check_in_date)
);

-- RLS Policies
ALTER TABLE daily_check_ins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own check-ins"
    ON daily_check_ins FOR SELECT
    USING (auth.uid() = user_id);

-- Function to handle daily check-in
CREATE OR REPLACE FUNCTION daily_check_in(p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_last_check_in DATE;
    v_consecutive_days INTEGER;
    v_reward INTEGER := 10; -- Base reward
    v_bonus INTEGER := 0;
BEGIN
    -- Check if already checked in today
    IF EXISTS (
        SELECT 1 FROM daily_check_ins 
        WHERE user_id = p_user_id AND check_in_date = CURRENT_DATE
    ) THEN
        RETURN jsonb_build_object(
            'success', false, 
            'message', '今日已簽到'
        );
    END IF;

    -- Calculate consecutive days (simplified logic for now)
    -- This is a placeholder for more complex logic if needed
    
    -- Insert check-in record
    INSERT INTO daily_check_ins (user_id, check_in_date, reward_amount)
    VALUES (p_user_id, CURRENT_DATE, v_reward);

    -- Update user tokens
    UPDATE users 
    SET tokens = COALESCE(tokens, 0) + v_reward
    WHERE id = p_user_id;

    RETURN jsonb_build_object(
        'success', true, 
        'message', 'Check-in successful',
        'reward', v_reward
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get check-in status (last 7 days)
CREATE OR REPLACE FUNCTION get_check_in_status(p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_check_ins JSONB;
    v_today_checked BOOLEAN;
BEGIN
    SELECT jsonb_agg(jsonb_build_object(
        'date', check_in_date,
        'reward', reward_amount
    ))
    INTO v_check_ins
    FROM (
        SELECT check_in_date, reward_amount
        FROM daily_check_ins
        WHERE user_id = p_user_id
        ORDER BY check_in_date DESC
        LIMIT 7
    ) t;

    SELECT EXISTS (
        SELECT 1 FROM daily_check_ins 
        WHERE user_id = p_user_id AND check_in_date = CURRENT_DATE
    ) INTO v_today_checked;

    RETURN jsonb_build_object(
        'history', COALESCE(v_check_ins, '[]'::jsonb),
        'today_checked', v_today_checked
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
