-- Fix missing tables and functions for Gachapon System

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Ensure Products and Prizes exist
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code TEXT UNIQUE,
  name TEXT NOT NULL,
  image_url TEXT,
  category TEXT DEFAULT '一番賞',
  price INTEGER NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('active', 'pending', 'ended')),
  is_hot BOOLEAN DEFAULT false,
  total_count INTEGER DEFAULT 0,
  remaining_count INTEGER DEFAULT 0,
  release_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.prizes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  name TEXT NOT NULL,
  image_url TEXT,
  quantity INTEGER NOT NULL DEFAULT 0,
  probability FLOAT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create delivery_orders (Shipment Requests)
CREATE TABLE IF NOT EXISTS public.delivery_orders (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_name TEXT,
  recipient_phone TEXT,
  recipient_address TEXT,
  shipping_method TEXT DEFAULT 'standard',
  tracking_number TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'shipping', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create draw_history (Inventory)
CREATE TABLE IF NOT EXISTS public.draw_history (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  prize_id UUID REFERENCES public.prizes(id),
  ticket_no TEXT,
  status TEXT DEFAULT 'in_warehouse' CHECK (status IN ('in_warehouse', 'pending_delivery', 'shipped', 'exchanged')),
  delivery_order_id UUID REFERENCES public.delivery_orders(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  cost INTEGER DEFAULT 0
);

-- 5. Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.draw_history ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies

-- Products & Prizes: Public read
DROP POLICY IF EXISTS "Products are viewable by everyone" ON public.products;
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Prizes are viewable by everyone" ON public.prizes;
CREATE POLICY "Prizes are viewable by everyone" ON public.prizes FOR SELECT USING (true);

-- Delivery Orders: Users view/create own
DROP POLICY IF EXISTS "Users can view own delivery orders" ON public.delivery_orders;
CREATE POLICY "Users can view own delivery orders" ON public.delivery_orders FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own delivery orders" ON public.delivery_orders;
CREATE POLICY "Users can insert own delivery orders" ON public.delivery_orders FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own delivery orders" ON public.delivery_orders;
CREATE POLICY "Users can update own delivery orders" ON public.delivery_orders FOR UPDATE USING (auth.uid() = user_id);

-- Draw History: Users view own
DROP POLICY IF EXISTS "Users can view own draw history" ON public.draw_history;
CREATE POLICY "Users can view own draw history" ON public.draw_history FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own draw history" ON public.draw_history;
CREATE POLICY "Users can update own draw history" ON public.draw_history FOR UPDATE USING (auth.uid() = user_id);

-- 7. Create play_ichiban function
CREATE OR REPLACE FUNCTION public.play_ichiban(p_product_id BIGINT, p_count INTEGER)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_product_price INTEGER;
  v_user_points INTEGER;
  v_total_cost INTEGER;
  v_prize RECORD;
  v_prizes_drawn JSONB := '[]'::jsonb;
  v_i INTEGER;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Check product and price
  SELECT price INTO v_product_price FROM products WHERE id = p_product_id;
  IF v_product_price IS NULL THEN
    RAISE EXCEPTION 'Product not found';
  END IF;

  v_total_cost := v_product_price * p_count;

  -- Check user points (Optional: Uncomment if you implement points)
  -- SELECT points INTO v_user_points FROM profiles WHERE id = v_user_id;
  -- IF v_user_points < v_total_cost THEN
  --   RAISE EXCEPTION 'Insufficient points';
  -- END IF;
  
  -- Deduct points (Optional)
  -- UPDATE profiles SET points = points - v_total_cost WHERE id = v_user_id;

  -- Draw Logic
  FOR v_i IN 1..p_count LOOP
    -- Pick a random prize from available prizes
    SELECT * INTO v_prize FROM prizes 
    WHERE product_id = p_product_id AND quantity > 0
    ORDER BY random() * probability DESC
    LIMIT 1;

    IF v_prize IS NULL THEN
      -- Fallback if no prizes with quantity > 0 (Should handle gracefully, but for now raise error)
      -- Or try to find any prize?
      RAISE EXCEPTION 'No prizes left';
    END IF;

    -- Decrement quantity
    UPDATE prizes SET quantity = quantity - 1 WHERE id = v_prize.id;
    UPDATE products SET remaining_count = remaining_count - 1 WHERE id = p_product_id;

    -- Record in draw_history
    INSERT INTO draw_history (user_id, product_id, prize_id, ticket_no, cost)
    VALUES (v_user_id, p_product_id, v_prize.id, (floor(random() * 10000)::text), v_product_price);

    -- Add to result
    v_prizes_drawn := v_prizes_drawn || jsonb_build_object(
      'grade', v_prize.grade,
      'name', v_prize.name,
      'image_url', v_prize.image_url
    );
  END LOOP;

  RETURN v_prizes_drawn;
END;
$$;

-- Grant permissions
GRANT ALL ON public.products TO authenticated;
GRANT ALL ON public.prizes TO authenticated;
GRANT ALL ON public.delivery_orders TO authenticated;
GRANT ALL ON public.draw_history TO authenticated;
GRANT EXECUTE ON FUNCTION public.play_ichiban TO authenticated;
GRANT ALL ON public.products TO anon;
GRANT ALL ON public.prizes TO anon;
