-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create BANNERS table if not exists
CREATE TABLE IF NOT EXISTS public.banners (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  image_url TEXT NOT NULL,
  link_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true
);

-- 2. Create PRODUCTS table if not exists
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code TEXT UNIQUE,
  name TEXT NOT NULL,
  image_url TEXT,
  category TEXT DEFAULT '一番賞',
  price INTEGER NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('active', 'pending', 'ended')),
  is_hot BOOLEAN DEFAULT false,
  total_count INTEGER DEFAULT 0,
  remaining_count INTEGER DEFAULT 0,
  release_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create PRIZES table if not exists
CREATE TABLE IF NOT EXISTS public.prizes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  grade TEXT NOT NULL, -- A, B, C, Last One
  name TEXT NOT NULL,
  image_url TEXT,
  quantity INTEGER NOT NULL DEFAULT 0,
  probability FLOAT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create PROFILES table if not exists (MISSING PART)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  email TEXT,
  avatar_url TEXT,
  points INTEGER DEFAULT 0,
  recipient_name TEXT,
  recipient_phone TEXT,
  recipient_address TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'banned')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, avatar_url, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user')
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Step 0: Remove duplicates if any exist, to allow adding Unique Constraint
-- (Only if table already existed and had data)
DELETE FROM public.products a USING public.products b
WHERE a.id < b.id AND a.product_code = b.product_code;

-- Step 1: Ensure product_code has a unique constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_constraint 
        WHERE conname = 'products_product_code_key'
    ) THEN
        ALTER TABLE public.products ADD CONSTRAINT products_product_code_key UNIQUE (product_code);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Constraint might already exist or data violation: %', SQLERRM;
END $$;

-- Step 2: Ensure columns exist (Double check in case table existed but old schema)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS total_count INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS remaining_count INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS release_date DATE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_hot BOOLEAN DEFAULT false;

-- Step 3: Insert 5 Banners
INSERT INTO public.banners (image_url, link_url, sort_order, is_active)
SELECT 
  'https://placehold.co/1200x298/cccccc/000000/png?text=1200x298',
  '/shop',
  i,
  true
FROM generate_series(1, 5) as i;

-- Step 4: Insert 20 Products and their Prizes
DO $$
DECLARE
  i INTEGER;
  v_product_id BIGINT;
BEGIN
  FOR i IN 1..20 LOOP
    -- Insert Product
    INSERT INTO public.products (
      product_code, 
      name, 
      image_url, 
      category, 
      price, 
      status, 
      is_hot, 
      total_count, 
      remaining_count, 
      release_date
    )
    VALUES (
      (10000000 + i)::text,
      '測試商品 ' || i,
      'https://placehold.co/400x400/cccccc/000000/png?text=400x400',
      '一番賞',
      250,
      'active',
      (i % 5 = 0),
      80,
      80,
      NOW()
    )
    ON CONFLICT (product_code) DO UPDATE 
    SET name = EXCLUDED.name -- Dummy update to ensure we can get ID
    RETURNING id INTO v_product_id;

    -- If product was inserted (or updated), v_product_id will be set. 
    -- If ON CONFLICT DO NOTHING, v_product_id might be null if it already existed.
    -- To be safe, let's select it if null.
    IF v_product_id IS NULL THEN
      SELECT id INTO v_product_id FROM public.products WHERE product_code = (10000000 + i)::text;
    END IF;

    -- Check if prizes exist, if not insert them
    IF NOT EXISTS (SELECT 1 FROM public.prizes WHERE product_id = v_product_id) THEN
        -- Insert Prizes (Total 80 items)
        
        -- A Prize (1 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'A', 'A賞 模型', 'https://placehold.co/400x400/cccccc/000000/png?text=A', 1, 1.25);
        
        -- B Prize (2 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'B', 'B賞 模型', 'https://placehold.co/400x400/cccccc/000000/png?text=B', 2, 2.5);

        -- C Prize (2 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'C', 'C賞 公仔', 'https://placehold.co/400x400/cccccc/000000/png?text=C', 2, 2.5);

        -- D Prize (5 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'D', 'D賞 毛巾', 'https://placehold.co/400x400/cccccc/000000/png?text=D', 5, 6.25);

        -- E Prize (10 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'E', 'E賞 杯子', 'https://placehold.co/400x400/cccccc/000000/png?text=E', 10, 12.5);

        -- F Prize (20 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'F', 'F賞 資料夾', 'https://placehold.co/400x400/cccccc/000000/png?text=F', 20, 25.0);

        -- G Prize (40 qty)
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'G', 'G賞 吊飾', 'https://placehold.co/400x400/cccccc/000000/png?text=G', 40, 50.0);

        -- Last One
        INSERT INTO public.prizes (product_id, grade, name, image_url, quantity, probability)
        VALUES (v_product_id, 'Last One', '最後賞', 'https://placehold.co/400x400/cccccc/000000/png?text=Last', 1, 0);
    END IF;
    
  END LOOP;
END $$;
