-- 0. Ensure product_prizes exists (some environments may not have migrated yet)
CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  email TEXT,
  avatar_url TEXT,
  points INTEGER DEFAULT 0,
  phone_number TEXT,
  is_phone_verified BOOLEAN DEFAULT false,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  price INTEGER NOT NULL DEFAULT 0,
  type TEXT NOT NULL CHECK (type IN ('ichiban', 'blindbox', 'gacha', 'card', 'custom')),
  status TEXT DEFAULT 'active',
  is_active BOOLEAN DEFAULT true,
  category_id UUID REFERENCES categories(id),
  total_count INTEGER DEFAULT 0,
  remaining_count INTEGER DEFAULT 0,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS product_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  level VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  image_url TEXT,
  total INTEGER NOT NULL,
  remaining INTEGER NOT NULL,
  probability NUMERIC(5, 2) NOT NULL,
  recycle_value INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_ticket_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  ticket_count INTEGER NOT NULL,
  price INTEGER NOT NULL,
  currency TEXT DEFAULT 'TWD',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id UUID REFERENCES auth.users(id),
  status TEXT NOT NULL DEFAULT 'pending',
  total_amount INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  logistics_type VARCHAR(20) DEFAULT 'HOME',
  logistics_subtype VARCHAR(20),
  store_id VARCHAR(50),
  store_name VARCHAR(100),
  recipient_name TEXT,
  recipient_phone TEXT,
  recipient_address TEXT,
  logistics_status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_prize_id BIGINT REFERENCES product_prizes(id),
  price INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS draw_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  product_id BIGINT REFERENCES products(id),
  product_prize_id BIGINT REFERENCES product_prizes(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  link_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  condition_type TEXT NOT NULL,
  condition_value INTEGER DEFAULT 1,
  reward_points INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_task_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  task_id BIGINT REFERENCES tasks(id),
  current_value INTEGER DEFAULT 0,
  is_completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS daily_check_ins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  check_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_amount INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  coupon_id BIGINT REFERENCES coupons(id),
  is_used BOOLEAN DEFAULT false,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1. Disable triggers to avoid foreign key checks during truncation
SET session_replication_role = 'replica';

-- 2. Truncate all main tables
TRUNCATE TABLE product_prizes CASCADE;
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE product_ticket_plan CASCADE;
TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE order_items CASCADE;
TRUNCATE TABLE draw_records CASCADE;
TRUNCATE TABLE banners CASCADE;
TRUNCATE TABLE news CASCADE;
TRUNCATE TABLE tasks CASCADE;
TRUNCATE TABLE user_task_progress CASCADE;
TRUNCATE TABLE daily_check_ins CASCADE;
TRUNCATE TABLE coupons CASCADE;
TRUNCATE TABLE user_coupons CASCADE;

-- 3. Re-enable triggers
SET session_replication_role = 'origin';

-- 4. Update product type constraint to include 'custom'
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_type_check;
ALTER TABLE products ADD CONSTRAINT products_type_check CHECK (type IN ('ichiban', 'blindbox', 'gacha', 'card', 'custom'));

-- 4.0 Update Users Table (Add Points and Phone Verification)
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_phone_verified BOOLEAN DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cvs_store_id TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cvs_store_name TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cvs_store_address TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cvs_recipient_name TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS cvs_recipient_phone TEXT;

-- 4.1 Ensure columns for公平性驗證存在
ALTER TABLE products ADD COLUMN IF NOT EXISTS txid_hash TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seed TEXT;

-- 4.2 啟用 pgcrypto 以便產生隨機 Seed 與 SHA256
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 4.3 Add recycle_value to product_prizes
ALTER TABLE product_prizes ADD COLUMN IF NOT EXISTS recycle_value INTEGER DEFAULT 0;

-- 4.4 Add Logistics columns to orders
ALTER TABLE orders ADD COLUMN IF NOT EXISTS logistics_type VARCHAR(20) DEFAULT 'HOME';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS logistics_subtype VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS store_id VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS store_name VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recipient_name TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recipient_phone TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recipient_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS logistics_status TEXT DEFAULT 'pending';

-- 4.5 Add Payment Method to recharge_records
ALTER TABLE recharge_records ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);

-- 4.6 Mission System Schema Updates
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_condition_type_check;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_condition_type_check 
  CHECK (condition_type IN ('login', 'draw_count', 'spend_amount', 'share_app', 'view_product', 'like_ranking', 'recharge', 'win_sr', 'play_unique_machine', 'bind_phone', 'sell_item'));
ALTER TABLE public.user_task_progress ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

-- 4.7 Worship System Schema
CREATE TABLE IF NOT EXISTS worship_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worshipper_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  worship_date DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_worship_daily_limit ON worship_logs (worshipper_id, worship_date);

-- 5. Insert Categories (Operation Themes)
WITH cats AS (
  INSERT INTO categories (name, sort_order, is_active) VALUES 
  ('馬年大促銷', 1, true),
  ('情人節限定', 2, true),
  ('年末出清【限時】', 3, true),
  ('人氣動漫專區', 4, true),
  ('3C 數位大賞', 5, true)
  RETURNING id, name
)
SELECT * INTO TEMP TABLE temp_cats FROM cats;

-- Helper function to get category ID
DROP FUNCTION IF EXISTS get_cat_id(text);
CREATE OR REPLACE FUNCTION get_cat_id(cat_name text) RETURNS uuid AS $$
  SELECT id FROM temp_cats WHERE name = cat_name LIMIT 1;
$$ LANGUAGE sql;

INSERT INTO products (
  product_code, name, category, category_id, price, status, is_hot,
  total_count, remaining, image_url, type, major_prizes,
  distributor, release_year, release_month, seed, txid_hash
)
SELECT
  product_code,
  name,
  category,
  get_cat_id(category),
  price,
  status,
  is_hot,
  total_count,
  total_count,
  image_url,
  type,
  major_prizes,
  distributor,
  release_year,
  release_month,
  seed,
  encode(digest(seed, 'sha256'), 'hex')
FROM (
  VALUES
    ('10000001', '一番賞 海賊王 未來的島嶼', '人氣動漫專區', 350, 'active', true, 80, '/images/item/10001.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '03', encode(gen_random_bytes(32), 'hex')),
    ('10000002', '一番賞 七龍珠 激戰歷史', '年末出清【限時】', 300, 'active', false, 80, '/images/item/10002.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2024', '12', encode(gen_random_bytes(32), 'hex')),
    ('10000003', '一番賞 火影忍者 疾風傳 忍界大戰', '人氣動漫專區', 320, 'active', true, 80, '/images/item/10003.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '01', encode(gen_random_bytes(32), 'hex')),
    ('10000004', '一番賞 鬼滅之刃 柱訓練', '人氣動漫專區', 300, 'active', true, 80, '/images/item/10004.jpg', 'ichiban', ARRAY['A賞']::text[], 'Banpresto', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000005', '一番賞 SPY×FAMILY 間諜家家酒 甜蜜約會', '情人節限定', 330, 'active', true, 80, '/images/item/10005.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000006', '一番賞 福音戰士 新劇場版', '馬年大促銷', 280, 'active', false, 80, '/images/item/10006.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '01', encode(gen_random_bytes(32), 'hex')),
    ('10000007', '一番賞 咒術迴戰 澀谷事變', '人氣動漫專區', 310, 'active', true, 80, '/images/item/10007.jpg', 'ichiban', ARRAY['A賞']::text[], 'Banpresto', '2025', '03', encode(gen_random_bytes(32), 'hex')),
    ('10000008', '一番賞 三麗鷗角色 巧克力派對', '情人節限定', 250, 'active', false, 80, '/images/item/10008.jpg', 'ichiban', ARRAY['A賞']::text[], 'Sanrio', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000009', '一番賞 機動戰士鋼彈 SEED FREEDOM', '馬年大促銷', 360, 'active', true, 80, '/images/item/10009.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '01', encode(gen_random_bytes(32), 'hex')),
    ('10000010', '一番賞 Hololive Production Vol.4', '人氣動漫專區', 380, 'active', true, 80, '/images/item/10010.jpg', 'ichiban', ARRAY['A賞']::text[], 'Bandai', '2025', '03', encode(gen_random_bytes(32), 'hex')),

    ('10000011', '盒玩：泡泡瑪特 SKULLPANDA 溫度系列', '馬年大促銷', 380, 'active', true, 12, '/images/item/10011.jpg', 'blindbox', ARRAY['隱藏款']::text[], 'POP MART', '2025', '01', encode(gen_random_bytes(32), 'hex')),
    ('10000012', '盒玩：MOLLY 甜點系列', '情人節限定', 360, 'active', true, 12, '/images/item/10012.jpg', 'blindbox', ARRAY['隱藏款']::text[], 'POP MART', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000013', '盒玩：DIMOO 動物派對', '人氣動漫專區', 350, 'active', false, 12, '/images/item/10013.jpg', 'blindbox', ARRAY['隱藏款']::text[], 'POP MART', '2025', '03', encode(gen_random_bytes(32), 'hex')),

    ('10000014', '轉蛋：動物森友會 造型轉蛋', '人氣動漫專區', 150, 'active', false, 50, '/images/item/10014.jpg', 'gacha', ARRAY['Secret']::text[], 'Takara Tomy', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000015', '轉蛋：寶可夢角色公仔轉蛋', '人氣動漫專區', 160, 'active', true, 50, '/images/item/10015.jpg', 'gacha', ARRAY['Secret']::text[], 'The Pokémon Company', '2025', '03', encode(gen_random_bytes(32), 'hex')),
    ('10000016', '轉蛋：三麗鷗角色小物轉蛋', '情人節限定', 140, 'active', false, 50, '/images/item/10016.jpg', 'gacha', ARRAY['Secret']::text[], 'Sanrio', '2025', '02', encode(gen_random_bytes(32), 'hex')),

    ('10000017', '抽卡：寶可夢集換式卡牌', '人氣動漫專區', 180, 'active', true, 30, '/images/item/10017.jpg', 'card', ARRAY['SSR','UR','LR']::text[], 'The Pokémon Company', '2025', '03', encode(gen_random_bytes(32), 'hex')),
    ('10000018', '抽卡：航海王卡牌對戰', '人氣動漫專區', 200, 'active', true, 30, '/images/item/10018.jpg', 'card', ARRAY['SSR','UR','LR']::text[], 'Bandai', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000019', '抽卡：七龍珠 Fusion World', '人氣動漫專區', 220, 'active', true, 30, '/images/item/10019.jpg', 'card', ARRAY['SSR','UR','LR']::text[], 'Bandai', '2025', '03', encode(gen_random_bytes(32), 'hex')),

    ('10000020', '自製賞：3C 大禮包', '3C 數位大賞', 500, 'active', true, 50, '/images/item/10020.jpg', 'custom', ARRAY['A賞']::text[], 'Slime Inc.', '2025', '01', encode(gen_random_bytes(32), 'hex')),
    ('10000021', '自製賞：情人節甜蜜禮盒', '情人節限定', 420, 'active', true, 50, '/images/item/10021.jpg', 'custom', ARRAY['A賞']::text[], 'Slime Inc.', '2025', '02', encode(gen_random_bytes(32), 'hex')),
    ('10000022', '自製賞：馬年大促銷福袋', '馬年大促銷', 360, 'active', false, 50, '/images/item/10022.jpg', 'custom', ARRAY['A賞']::text[], 'Slime Inc.', '2025', '01', encode(gen_random_bytes(32), 'hex'))
) AS v(
  product_code, name, category, price, status, is_hot,
  total_count, image_url, type, major_prizes,
  distributor, release_year, release_month, seed
);

INSERT INTO product_prizes (product_id, level, name, image_url, total, remaining, probability, recycle_value)
SELECT
  p.id,
  v.level,
  v.prize_name,
  p.image_url,
  v.total,
  v.total,
  0,
  v.recycle_value
FROM products p
JOIN (
  VALUES
    ('10000001', 'A賞', 'A賞 獎品', 2, 800),
    ('10000001', 'B賞', 'B賞 獎品', 2, 600),
    ('10000001', 'C賞', 'C賞 獎品', 4, 400),
    ('10000001', 'D賞', 'D賞 獎品', 4, 300),
    ('10000001', 'E賞', 'E賞 小物', 12, 50),
    ('10000001', 'F賞', 'F賞 小物', 16, 50),
    ('10000001', 'G賞', 'G賞 小物', 16, 50),
    ('10000001', 'H賞', 'H賞 小物', 12, 50),
    ('10000001', 'I賞', 'I賞 小物', 8, 50),
    ('10000001', 'J賞', 'J賞 小物', 4, 50),
    ('10000001', '最後賞', '最後賞', 1, 1000),

    ('10000002', 'A賞', 'A賞 獎品', 2, 800),
    ('10000002', 'B賞', 'B賞 獎品', 2, 600),
    ('10000002', 'C賞', 'C賞 獎品', 4, 400),
    ('10000002', 'D賞', 'D賞 獎品', 4, 300),
    ('10000002', 'E賞', 'E賞 小物', 12, 50),
    ('10000002', 'F賞', 'F賞 小物', 16, 50),
    ('10000002', 'G賞', 'G賞 小物', 16, 50),
    ('10000002', 'H賞', 'H賞 小物', 12, 50),
    ('10000002', 'I賞', 'I賞 小物', 8, 50),
    ('10000002', 'J賞', 'J賞 小物', 4, 50),
    ('10000002', '最後賞', '最後賞', 1, 1000),

    ('10000003', 'A賞', 'A賞 獎品', 2, 800),
    ('10000003', 'B賞', 'B賞 獎品', 2, 600),
    ('10000003', 'C賞', 'C賞 獎品', 4, 400),
    ('10000003', 'D賞', 'D賞 獎品', 4, 300),
    ('10000003', 'E賞', 'E賞 小物', 12, 50),
    ('10000003', 'F賞', 'F賞 小物', 16, 50),
    ('10000003', 'G賞', 'G賞 小物', 16, 50),
    ('10000003', 'H賞', 'H賞 小物', 12, 50),
    ('10000003', 'I賞', 'I賞 小物', 8, 50),
    ('10000003', 'J賞', 'J賞 小物', 4, 50),
    ('10000003', '最後賞', '最後賞', 1, 1000),

    ('10000004', 'A賞', 'A賞 獎品', 2, 800),
    ('10000004', 'B賞', 'B賞 獎品', 2, 600),
    ('10000004', 'C賞', 'C賞 獎品', 4, 400),
    ('10000004', 'D賞', 'D賞 獎品', 4, 300),
    ('10000004', 'E賞', 'E賞 小物', 12, 50),
    ('10000004', 'F賞', 'F賞 小物', 16, 50),
    ('10000004', 'G賞', 'G賞 小物', 16, 50),
    ('10000004', 'H賞', 'H賞 小物', 12, 50),
    ('10000004', 'I賞', 'I賞 小物', 8, 50),
    ('10000004', 'J賞', 'J賞 小物', 4, 50),
    ('10000004', '最後賞', '最後賞', 1, 1000),

    ('10000005', 'A賞', 'A賞 獎品', 2, 800),
    ('10000005', 'B賞', 'B賞 獎品', 2, 600),
    ('10000005', 'C賞', 'C賞 獎品', 4, 400),
    ('10000005', 'D賞', 'D賞 獎品', 4, 300),
    ('10000005', 'E賞', 'E賞 小物', 12, 50),
    ('10000005', 'F賞', 'F賞 小物', 16, 50),
    ('10000005', 'G賞', 'G賞 小物', 16, 50),
    ('10000005', 'H賞', 'H賞 小物', 12, 50),
    ('10000005', 'I賞', 'I賞 小物', 8, 50),
    ('10000005', 'J賞', 'J賞 小物', 4, 50),
    ('10000005', '最後賞', '最後賞', 1, 1000),

    ('10000006', 'A賞', 'A賞 獎品', 2, 800),
    ('10000006', 'B賞', 'B賞 獎品', 2, 600),
    ('10000006', 'C賞', 'C賞 獎品', 4, 400),
    ('10000006', 'D賞', 'D賞 獎品', 4, 300),
    ('10000006', 'E賞', 'E賞 小物', 12, 50),
    ('10000006', 'F賞', 'F賞 小物', 16, 50),
    ('10000006', 'G賞', 'G賞 小物', 16, 50),
    ('10000006', 'H賞', 'H賞 小物', 12, 50),
    ('10000006', 'I賞', 'I賞 小物', 8, 50),
    ('10000006', 'J賞', 'J賞 小物', 4, 50),
    ('10000006', '最後賞', '最後賞', 1, 1000),

    ('10000007', 'A賞', 'A賞 獎品', 2, 800),
    ('10000007', 'B賞', 'B賞 獎品', 2, 600),
    ('10000007', 'C賞', 'C賞 獎品', 4, 400),
    ('10000007', 'D賞', 'D賞 獎品', 4, 300),
    ('10000007', 'E賞', 'E賞 小物', 12, 50),
    ('10000007', 'F賞', 'F賞 小物', 16, 50),
    ('10000007', 'G賞', 'G賞 小物', 16, 50),
    ('10000007', 'H賞', 'H賞 小物', 12, 50),
    ('10000007', 'I賞', 'I賞 小物', 8, 50),
    ('10000007', 'J賞', 'J賞 小物', 4, 50),
    ('10000007', '最後賞', '最後賞', 1, 1000),

    ('10000008', 'A賞', 'A賞 獎品', 2, 800),
    ('10000008', 'B賞', 'B賞 獎品', 2, 600),
    ('10000008', 'C賞', 'C賞 獎品', 4, 400),
    ('10000008', 'D賞', 'D賞 獎品', 4, 300),
    ('10000008', 'E賞', 'E賞 小物', 12, 50),
    ('10000008', 'F賞', 'F賞 小物', 16, 50),
    ('10000008', 'G賞', 'G賞 小物', 16, 50),
    ('10000008', 'H賞', 'H賞 小物', 12, 50),
    ('10000008', 'I賞', 'I賞 小物', 8, 50),
    ('10000008', 'J賞', 'J賞 小物', 4, 50),
    ('10000008', '最後賞', '最後賞', 1, 1000),

    ('10000009', 'A賞', 'A賞 獎品', 2, 800),
    ('10000009', 'B賞', 'B賞 獎品', 2, 600),
    ('10000009', 'C賞', 'C賞 獎品', 4, 400),
    ('10000009', 'D賞', 'D賞 獎品', 4, 300),
    ('10000009', 'E賞', 'E賞 小物', 12, 50),
    ('10000009', 'F賞', 'F賞 小物', 16, 50),
    ('10000009', 'G賞', 'G賞 小物', 16, 50),
    ('10000009', 'H賞', 'H賞 小物', 12, 50),
    ('10000009', 'I賞', 'I賞 小物', 8, 50),
    ('10000009', 'J賞', 'J賞 小物', 4, 50),
    ('10000009', '最後賞', '最後賞', 1, 1000),

    ('10000010', 'A賞', 'A賞 獎品', 2, 800),
    ('10000010', 'B賞', 'B賞 獎品', 2, 600),
    ('10000010', 'C賞', 'C賞 獎品', 4, 400),
    ('10000010', 'D賞', 'D賞 獎品', 4, 300),
    ('10000010', 'E賞', 'E賞 小物', 12, 50),
    ('10000010', 'F賞', 'F賞 小物', 16, 50),
    ('10000010', 'G賞', 'G賞 小物', 16, 50),
    ('10000010', 'H賞', 'H賞 小物', 12, 50),
    ('10000010', 'I賞', 'I賞 小物', 8, 50),
    ('10000010', 'J賞', 'J賞 小物', 4, 50),
    ('10000010', '最後賞', '最後賞', 1, 1000),

    ('10000011', '普通款', '普通款', 9, 30),
    ('10000011', '稀有款', '稀有款', 2, 80),
    ('10000011', '隱藏款', '隱藏款', 1, 300),

    ('10000012', '普通款', '普通款', 9, 30),
    ('10000012', '稀有款', '稀有款', 2, 80),
    ('10000012', '隱藏款', '隱藏款', 1, 300),

    ('10000013', '普通款', '普通款', 9, 30),
    ('10000013', '稀有款', '稀有款', 2, 80),
    ('10000013', '隱藏款', '隱藏款', 1, 300),

    ('10000014', '一般', '一般版 Normal / Common', 38, 10),
    ('10000014', '稀有', '稀有版 Rare', 10, 30),
    ('10000014', '隱藏', '隱藏版 Secret', 2, 200),

    ('10000015', '一般', '一般版 Normal / Common', 38, 10),
    ('10000015', '稀有', '稀有版 Rare', 10, 30),
    ('10000015', '隱藏', '隱藏版 Secret', 2, 200),

    ('10000016', '一般', '一般版 Normal / Common', 38, 10),
    ('10000016', '稀有', '稀有版 Rare', 10, 30),
    ('10000016', '隱藏', '隱藏版 Secret', 2, 200),

    ('10000017', 'N', 'N', 14, 5),
    ('10000017', 'R', 'R', 8, 20),
    ('10000017', 'SR', 'SR', 4, 80),
    ('10000017', 'SSR', 'SSR', 2, 200),
    ('10000017', 'UR', 'UR', 1, 500),
    ('10000017', 'LR', 'LR', 1, 800),

    ('10000018', 'N', 'N', 14, 5),
    ('10000018', 'R', 'R', 8, 20),
    ('10000018', 'SR', 'SR', 4, 80),
    ('10000018', 'SSR', 'SSR', 2, 200),
    ('10000018', 'UR', 'UR', 1, 500),
    ('10000018', 'LR', 'LR', 1, 800),

    ('10000019', 'N', 'N', 14, 5),
    ('10000019', 'R', 'R', 8, 20),
    ('10000019', 'SR', 'SR', 4, 80),
    ('10000019', 'SSR', 'SSR', 2, 200),
    ('10000019', 'UR', 'UR', 1, 500),
    ('10000019', 'LR', 'LR', 1, 800),

    ('10000020', 'A賞', 'A賞 獎品', 1, 800),
    ('10000020', 'B賞', 'B賞 獎品', 1, 600),
    ('10000020', 'C賞', 'C賞 獎品', 2, 400),
    ('10000020', 'D賞', 'D賞 獎品', 2, 300),
    ('10000020', 'E賞', 'E賞 小物', 8, 50),
    ('10000020', 'F賞', 'F賞 小物', 10, 50),
    ('10000020', 'G賞', 'G賞 小物', 10, 50),
    ('10000020', 'H賞', 'H賞 小物', 8, 50),
    ('10000020', 'I賞', 'I賞 小物', 6, 50),
    ('10000020', 'J賞', 'J賞 小物', 2, 50),
    ('10000020', '最後賞', '最後賞', 1, 1000),

    ('10000021', 'A賞', 'A賞 獎品', 1, 800),
    ('10000021', 'B賞', 'B賞 獎品', 1, 600),
    ('10000021', 'C賞', 'C賞 獎品', 2, 400),
    ('10000021', 'D賞', 'D賞 獎品', 2, 300),
    ('10000021', 'E賞', 'E賞 小物', 8, 50),
    ('10000021', 'F賞', 'F賞 小物', 10, 50),
    ('10000021', 'G賞', 'G賞 小物', 10, 50),
    ('10000021', 'H賞', 'H賞 小物', 8, 50),
    ('10000021', 'I賞', 'I賞 小物', 6, 50),
    ('10000021', 'J賞', 'J賞 小物', 2, 50),
    ('10000021', '最後賞', '最後賞', 1, 1000),

    ('10000022', 'A賞', 'A賞 獎品', 1, 800),
    ('10000022', 'B賞', 'B賞 獎品', 1, 600),
    ('10000022', 'C賞', 'C賞 獎品', 2, 400),
    ('10000022', 'D賞', 'D賞 獎品', 2, 300),
    ('10000022', 'E賞', 'E賞 小物', 8, 50),
    ('10000022', 'F賞', 'F賞 小物', 10, 50),
    ('10000022', 'G賞', 'G賞 小物', 10, 50),
    ('10000022', 'H賞', 'H賞 小物', 8, 50),
    ('10000022', 'I賞', 'I賞 小物', 6, 50),
    ('10000022', 'J賞', 'J賞 小物', 2, 50),
    ('10000022', '最後賞', '最後賞', 1, 1000)
) AS v(product_code, level, prize_name, total, recycle_value)
  ON p.product_code = v.product_code;

WITH totals AS (
  SELECT
    product_id,
    SUM(total) FILTER (WHERE level NOT IN ('最後賞', 'Last One', 'LAST ONE')) AS total_count
  FROM product_prizes
  GROUP BY product_id
)
UPDATE product_prizes pp
SET probability =
  CASE
    WHEN pp.level IN ('最後賞', 'Last One', 'LAST ONE') THEN 0
    ELSE ROUND((pp.total::numeric * 100.0) / NULLIF(t.total_count, 0), 2)
  END
FROM totals t
WHERE pp.product_id = t.product_id;

UPDATE products p
SET
  total_count = x.total_count,
  remaining = x.remaining
FROM (
  SELECT
    product_id,
    SUM(total) FILTER (WHERE level NOT IN ('最後賞', 'Last One', 'LAST ONE')) AS total_count,
    SUM(remaining) FILTER (WHERE level NOT IN ('最後賞', 'Last One', 'LAST ONE')) AS remaining
  FROM product_prizes
  GROUP BY product_id
) x
WHERE p.id = x.product_id;


-- ==========================================
-- UPDATE: Ensure process_topup uses standard ID format (TP + YYMMDD + Random)
-- ==========================================
DROP FUNCTION IF EXISTS process_topup(integer, integer);
DROP FUNCTION IF EXISTS process_topup(numeric, numeric);
DROP FUNCTION IF EXISTS process_topup(decimal, decimal);

CREATE OR REPLACE FUNCTION process_topup(
  p_amount DECIMAL,
  p_bonus DECIMAL
) RETURNS JSON AS $$
DECLARE
  v_user_id UUID;
  v_order_number VARCHAR(50);
  v_total_tokens INTEGER;
  v_new_balance INTEGER;
BEGIN
  v_user_id := auth.uid();
  
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Generate order number: TP + YYMMDD (6 digits) + Random 4 digits (Total 12 digits)
  v_order_number := 'TP' || to_char(now(), 'YYMMDD') || lpad(floor(random() * 10000)::text, 4, '0');
  
  v_total_tokens := p_amount + p_bonus;

  INSERT INTO recharge_records (
    order_number,
    user_id,
    amount,
    bonus,
    status
  ) VALUES (
    v_order_number,
    v_user_id,
    p_amount,
    p_bonus,
    'success'
  );

  UPDATE users
  SET tokens = tokens + v_total_tokens
  WHERE id = v_user_id
  RETURNING tokens INTO v_new_balance;

  -- Check if notifications table exists before inserting
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'notifications') THEN
    INSERT INTO notifications (
      user_id,
      type,
      title,
      body,
      link,
      meta
    )
    VALUES (
      v_user_id,
      'topup',
      '儲值成功通知',
      format('您成功儲值 %s 元，獲得 %s 代幣（含贈送 %s）', p_amount, v_total_tokens, p_bonus),
      '/profile?tab=topup-history',
      jsonb_build_object(
        'order_number', v_order_number,
        'amount', p_amount,
        'bonus', p_bonus,
        'added_tokens', v_total_tokens,
        'new_balance', v_new_balance
      )
    );
  END IF;

  RETURN json_build_object(
    'success', true,
    'order_number', v_order_number,
    'added_tokens', v_total_tokens,
    'new_balance', v_new_balance
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Initialize Fairness Seed for all new products
-- (Using txid_current() as a simple seed source, combined with random)
UPDATE products p
SET
  seed = s.seed,
  txid_hash = encode(digest(s.seed, 'sha256'), 'hex')
FROM (
  SELECT
    id,
    encode(gen_random_bytes(32), 'hex') AS seed
  FROM products
  WHERE seed IS NULL OR seed = '' OR txid_hash IS NULL OR txid_hash = ''
) s
WHERE p.id = s.id;

-- ==========================================
-- BANNERS
-- ==========================================
INSERT INTO banners (image_url, link_url, sort_order, is_active) VALUES
('/images/banner/1bankuji-brand_banner_pink_0321.jpg', '/products', 1, true),
('/images/banner/7DB_banner_1002-429_0614.jpg', '/products', 2, true),
('/images/banner/kimetsu_kuji.jpg', '/products', 3, true);

-- Create Mission System Tables

-- 1. Tasks Definition Table
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('daily', 'weekly', 'achievement')),
  title TEXT NOT NULL,
  description TEXT,
  target_value INTEGER NOT NULL DEFAULT 1,
  reward_coins INTEGER NOT NULL DEFAULT 0,
  condition_type TEXT NOT NULL CHECK (condition_type IN ('login', 'draw_count', 'spend_amount', 'share_app', 'view_product', 'like_ranking', 'recharge', 'win_sr', 'play_unique_machine', 'bind_phone', 'sell_item')),
  icon_name TEXT, -- Matches Lucide icon names (e.g., 'Ticket', 'Share', 'Trophy')
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. User Task Progress Table
CREATE TABLE IF NOT EXISTS public.user_task_progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  task_id UUID REFERENCES public.tasks(id) ON DELETE CASCADE,
  progress INTEGER DEFAULT 0,
  is_completed BOOLEAN DEFAULT false,
  is_claimed BOOLEAN DEFAULT false,
  period_key TEXT NOT NULL, -- e.g., '2023-10-27' for daily, '2023-W43' for weekly, 'ALL' for achievement
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_task_period UNIQUE (user_id, task_id, period_key)
);

-- 3. Enable RLS
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_task_progress ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Tasks are public read
DROP POLICY IF EXISTS "Tasks are viewable by everyone" ON public.tasks;
CREATE POLICY "Tasks are viewable by everyone" ON public.tasks FOR SELECT USING (true);

-- User Progress: Users can view their own progress
DROP POLICY IF EXISTS "Users can view own progress" ON public.user_task_progress;
CREATE POLICY "Users can view own progress" ON public.user_task_progress FOR SELECT USING (auth.uid() = user_id);

-- User Progress: Users can insert/update their own progress (for frontend tracking like 'share')
DROP POLICY IF EXISTS "Users can update own progress" ON public.user_task_progress;
CREATE POLICY "Users can update own progress" ON public.user_task_progress FOR ALL USING (auth.uid() = user_id);

-- 4.1 Insert Default Tasks
-- Daily Tasks (200 pts total)
INSERT INTO public.tasks (type, title, description, target_value, reward_coins, condition_type, icon_name) VALUES
('daily', '每日登入', '本日首次登入網站', 1, 10, 'login', 'Log-in'),
('daily', '瀏覽商品', '瀏覽 3 個不同的抽卡商品頁', 3, 10, 'view_product', 'Eye'),
('daily', '社群分享', '分享 1 次抽卡結果或商品連結', 1, 10, 'share_app', 'Share'),
('daily', '關注排行', '進入排行榜頁面並進行 1 次膜拜/按讚', 1, 10, 'like_ranking', 'Heart'),
('daily', '每日首抽', '完成 1 次任意商品抽卡', 1, 20, 'draw_count', 'Ticket'),
('daily', '累計抽卡 I', '本日累計完成 3 次抽卡', 3, 20, 'draw_count', 'Layers'),
('daily', '累計抽卡 II', '本日累計完成 5 次抽卡', 5, 30, 'draw_count', 'Layers'),
('daily', '累計抽卡 III', '本日累計完成 10 次抽卡', 10, 40, 'draw_count', 'Layers'),
('daily', '每日首儲', '本日完成任意金額代幣儲值', 1, 30, 'recharge', 'Wallet'),
('daily', '歐氣爆發', '本日獲得 1 次 SR (含) 以上獎項', 1, 20, 'win_sr', 'Sparkles');

-- Weekly Tasks (1000 pts total)
INSERT INTO public.tasks (type, title, description, target_value, reward_coins, condition_type, icon_name) VALUES
('weekly', '累計登入 I', '本週累計登入達 3 天', 3, 50, 'login', 'Calendar'),
('weekly', '累計登入 II', '本週累計登入達 5 天', 5, 50, 'login', 'Calendar'),
('weekly', '全勤報到', '本週累計登入達 7 天', 7, 100, 'login', 'Calendar-Check'),
('weekly', '廣泛探索', '本週參與過 3 種不同的抽卡機台/卡包', 3, 100, 'play_unique_machine', 'Compass'),
('weekly', '試試手氣', '本週累計完成 10 次抽卡', 10, 50, 'draw_count', 'Ticket'),
('weekly', '抽卡達人 I', '本週累計完成 30 次抽卡', 30, 100, 'draw_count', 'Layers'),
('weekly', '抽卡達人 II', '本週累計完成 50 次抽卡', 50, 150, 'draw_count', 'Layers'),
('weekly', '抽卡狂熱', '本週累計完成 100 次抽卡', 100, 200, 'draw_count', 'Layers'),
('weekly', '財富密碼', '本週累計消耗 5,000 代幣', 5000, 100, 'spend_amount', 'Coins'),
('weekly', '歐洲血統', '本週累計獲得 3 次 SR (含) 以上獎項', 3, 100, 'win_sr', 'Crown');

-- Achievement Tasks
INSERT INTO public.tasks (type, title, description, target_value, reward_coins, condition_type, icon_name) VALUES
('achievement', '手機驗證', '完成手機號碼綁定與驗證', 1, 50, 'bind_phone', 'Smartphone'),
('achievement', '不當免費仔', '完成首次儲值', 1, 100, 'recharge', 'Gem'),
('achievement', '完成一次上架', '在市集中完成一次商品上架', 1, 50, 'sell_item', 'Store');

-- 5. Helper Function: Claim Reward
DROP FUNCTION IF EXISTS claim_task_reward(uuid, text);
CREATE OR REPLACE FUNCTION claim_task_reward(p_task_id UUID, p_period_key TEXT)
RETURNS JSONB AS $$
DECLARE
  v_user_id UUID;
  v_task RECORD;
  v_progress RECORD;
BEGIN
  v_user_id := auth.uid();
  
  -- Get Task Info
  SELECT * INTO v_task FROM tasks WHERE id = p_task_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Task not found');
  END IF;

  -- Get Progress Info
  SELECT * INTO v_progress FROM user_task_progress 
  WHERE user_id = v_user_id AND task_id = p_task_id AND period_key = p_period_key;
  
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Progress not found');
  END IF;

  IF v_progress.is_claimed THEN
    RETURN jsonb_build_object('success', false, 'message', 'Already claimed');
  END IF;

  IF NOT v_progress.is_completed THEN
    -- Double check if progress meets target (in case trigger missed it)
    IF v_progress.progress >= v_task.target_value THEN
       UPDATE user_task_progress SET is_completed = true WHERE id = v_progress.id;
    ELSE
       RETURN jsonb_build_object('success', false, 'message', 'Task not completed');
    END IF;
  END IF;

  -- Add Coins
  UPDATE users SET points = points + v_task.reward_coins WHERE id = v_user_id;
  
  -- Mark Claimed
  UPDATE user_task_progress SET is_claimed = true WHERE id = v_progress.id;
  
  RETURN jsonb_build_object('success', true, 'reward', v_task.reward_coins);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Trigger for Daily Login (in public.users update or login tracking)
-- Note: Assuming there is a 'daily_check_ins' table or we use 'last_sign_in_at' from auth.users.
-- Since we cannot easily trigger off auth.users, we use a custom function called by frontend.

CREATE TABLE IF NOT EXISTS public.daily_check_ins (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  check_in_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_daily_checkin UNIQUE (user_id, check_in_date)
);

ALTER TABLE public.daily_check_ins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own check-ins" ON public.daily_check_ins;
CREATE POLICY "Users can view own check-ins" ON public.daily_check_ins FOR SELECT USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION daily_check_in(p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
  v_today DATE := CURRENT_DATE;
  v_task RECORD;
  v_week TEXT := to_char(NOW(), 'IYYY-IW');
BEGIN
  -- Insert check-in record
  INSERT INTO daily_check_ins (user_id, check_in_date) VALUES (p_user_id, v_today)
  ON CONFLICT DO NOTHING;
  
  IF NOT FOUND THEN
     RETURN jsonb_build_object('success', false, 'message', 'Already checked in today');
  END IF;

  -- Update Daily Task
  SELECT * INTO v_task FROM tasks WHERE condition_type = 'login' AND type = 'daily' AND is_active = true LIMIT 1;
  IF FOUND THEN
    INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
    VALUES (p_user_id, v_task.id, 1, to_char(v_today, 'YYYY-MM-DD'))
    ON CONFLICT (user_id, task_id, period_key) DO UPDATE SET progress = 1, last_updated = NOW();
    
    UPDATE user_task_progress SET is_completed = true 
    WHERE user_id = p_user_id AND task_id = v_task.id AND period_key = to_char(v_today, 'YYYY-MM-DD');
  END IF;

  -- Update Weekly Task (Count check-ins this week)
  DECLARE
    v_weekly_count INTEGER;
  BEGIN
    SELECT COUNT(*) INTO v_weekly_count FROM daily_check_ins 
    WHERE user_id = p_user_id AND check_in_date >= date_trunc('week', v_today)::date;
    
    FOR v_task IN SELECT * FROM tasks WHERE condition_type = 'login' AND type = 'weekly' AND is_active = true LOOP
      INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
      VALUES (p_user_id, v_task.id, v_weekly_count, v_week)
      ON CONFLICT (user_id, task_id, period_key) DO UPDATE SET progress = v_weekly_count, last_updated = NOW();
      
      UPDATE user_task_progress SET is_completed = true 
      WHERE user_id = p_user_id AND task_id = v_task.id AND period_key = v_week AND progress >= v_task.target_value AND is_completed = false;
    END LOOP;
  END;

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Check In Status Helper
DROP FUNCTION IF EXISTS public.get_check_in_status(uuid);
DROP FUNCTION IF EXISTS get_check_in_status(uuid);
CREATE OR REPLACE FUNCTION public.get_check_in_status(p_user_id UUID)
RETURNS BOOLEAN AS $$
  SELECT EXISTS(SELECT 1 FROM daily_check_ins WHERE user_id = p_user_id AND check_in_date = CURRENT_DATE);
$$ LANGUAGE sql SECURITY DEFINER;


-- 6. Trigger for Draw (Mission Progress)
CREATE OR REPLACE FUNCTION handle_new_draw_mission_progress()
RETURNS TRIGGER AS $$
DECLARE
  v_task RECORD;
  v_period_key TEXT;
  v_is_sr_up BOOLEAN;
BEGIN
  -- Determine if SR or above (Assuming 'A', 'B', 'Last One' etc are SR+)
  -- Adjust logic based on actual grade names
  v_is_sr_up := NEW.prize_level IN ('A賞', 'B賞', 'Last One', '最後賞', 'SP', 'SSR', 'UR');

  -- 1. Daily Tasks
  v_period_key := to_char(NEW.created_at, 'YYYY-MM-DD');
  
  FOR v_task IN SELECT * FROM tasks WHERE type = 'daily' AND is_active = true LOOP
    -- Condition: draw_count
    IF v_task.condition_type = 'draw_count' THEN
       INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
       VALUES (NEW.user_id, v_task.id, 1, v_period_key)
       ON CONFLICT (user_id, task_id, period_key) 
       DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    END IF;

    -- Condition: win_sr
    IF v_task.condition_type = 'win_sr' AND v_is_sr_up THEN
       INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
       VALUES (NEW.user_id, v_task.id, 1, v_period_key)
       ON CONFLICT (user_id, task_id, period_key) 
       DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    END IF;
    
    -- Check completion
    UPDATE user_task_progress 
    SET is_completed = true 
    WHERE user_id = NEW.user_id 
      AND task_id = v_task.id 
      AND period_key = v_period_key 
      AND progress >= v_task.target_value 
      AND is_completed = false;
      
  END LOOP;

  -- 2. Weekly Tasks
  v_period_key := to_char(NEW.created_at, 'IYYY-IW');
  
  FOR v_task IN SELECT * FROM tasks WHERE type = 'weekly' AND is_active = true LOOP
    -- Condition: draw_count
    IF v_task.condition_type = 'draw_count' THEN
       INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
       VALUES (NEW.user_id, v_task.id, 1, v_period_key)
       ON CONFLICT (user_id, task_id, period_key) 
       DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    END IF;
    
    -- Condition: spend_amount (Assume we have cost info, here we need product price. 
    -- Ideally draw_records should have cost. If not, we query product)
    IF v_task.condition_type = 'spend_amount' THEN
        -- Fetch price (Simplified: assuming we can get price easily. For now, we add 1 progress as placeholder or query)
        -- In real implementation, pass cost to draw_records or query products table
        -- Let's assume we update progress by 1 for now or implement properly if price is available
        -- Assuming NEW.profit_rate is not price. We need price.
        -- Skip for now or do a subquery
        DECLARE
           v_price INTEGER;
        BEGIN
           SELECT price INTO v_price FROM products WHERE id = NEW.product_id;
           IF v_price IS NOT NULL THEN
              INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
              VALUES (NEW.user_id, v_task.id, v_price, v_period_key)
              ON CONFLICT (user_id, task_id, period_key) 
              DO UPDATE SET progress = user_task_progress.progress + v_price, last_updated = NOW();
           END IF;
        END;
    END IF;

    -- Condition: play_unique_machine
    IF v_task.condition_type = 'play_unique_machine' THEN
        -- This requires tracking unique product_ids played this week.
        -- We can store the list in metadata JSONB
        DECLARE
           v_meta JSONB;
           v_pid TEXT := NEW.product_id::text;
           v_current_progress INT;
        BEGIN
           SELECT progress, metadata INTO v_current_progress, v_meta FROM user_task_progress 
           WHERE user_id = NEW.user_id AND task_id = v_task.id AND period_key = v_period_key;
           
           IF NOT FOUND THEN
             v_current_progress := 0;
             v_meta := '{"played_ids": []}'::jsonb;
           END IF;
           
           IF NOT (v_meta->'played_ids' ? v_pid) THEN
              v_meta := jsonb_set(v_meta, '{played_ids}', (v_meta->'played_ids') || to_jsonb(v_pid));
              INSERT INTO user_task_progress (user_id, task_id, progress, period_key, metadata)
              VALUES (NEW.user_id, v_task.id, 1, v_period_key, v_meta)
              ON CONFLICT (user_id, task_id, period_key) 
              DO UPDATE SET progress = jsonb_array_length(v_meta->'played_ids'), metadata = v_meta, last_updated = NOW();
           END IF;
        END;
    END IF;

    -- Condition: win_sr
    IF v_task.condition_type = 'win_sr' AND v_is_sr_up THEN
       INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
       VALUES (NEW.user_id, v_task.id, 1, v_period_key)
       ON CONFLICT (user_id, task_id, period_key) 
       DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    END IF;

    -- Check completion
    UPDATE user_task_progress 
    SET is_completed = true 
    WHERE user_id = NEW.user_id 
      AND task_id = v_task.id 
      AND period_key = v_period_key 
      AND progress >= v_task.target_value 
      AND is_completed = false;
      
  END LOOP;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_draw_mission ON draw_records;
CREATE TRIGGER trigger_draw_mission
AFTER INSERT ON draw_records
FOR EACH ROW
EXECUTE FUNCTION handle_new_draw_mission_progress();

-- 7. Trigger for Recharge (Top-up)
CREATE OR REPLACE FUNCTION handle_recharge_mission_progress()
RETURNS TRIGGER AS $$
DECLARE
  v_task RECORD;
  v_period_key TEXT;
BEGIN
  -- Assuming 'success' is the status for completed recharges
  IF NEW.status = 'success' AND (OLD.status IS NULL OR OLD.status != 'success') THEN
      
      -- Loop through Daily AND Achievement tasks
      FOR v_task IN SELECT * FROM tasks WHERE condition_type = 'recharge' AND is_active = true LOOP
        
        IF v_task.type = 'daily' THEN
           v_period_key := to_char(NEW.created_at, 'YYYY-MM-DD');
        ELSE -- Achievement or Weekly
           v_period_key := 'ALL';
        END IF;

        INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
        VALUES (NEW.user_id, v_task.id, 1, v_period_key)
        ON CONFLICT (user_id, task_id, period_key)
        DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
        
        -- Check completion
        UPDATE user_task_progress SET is_completed = true 
        WHERE user_id = NEW.user_id AND task_id = v_task.id AND period_key = v_period_key AND progress >= v_task.target_value AND is_completed = false;
      END LOOP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_recharge_mission ON recharge_records;
CREATE TRIGGER trigger_recharge_mission
AFTER UPDATE ON recharge_records
FOR EACH ROW
EXECUTE FUNCTION handle_recharge_mission_progress();

-- 8. Trigger for Phone Binding (User Update)
CREATE OR REPLACE FUNCTION handle_user_update_mission_progress()
RETURNS TRIGGER AS $$
DECLARE
  v_task RECORD;
BEGIN
  -- Check if is_phone_verified changed from false to true
  IF NEW.is_phone_verified = true AND (OLD.is_phone_verified IS NULL OR OLD.is_phone_verified = false) THEN
      FOR v_task IN SELECT * FROM tasks WHERE condition_type = 'bind_phone' AND type = 'achievement' AND is_active = true LOOP
        INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
        VALUES (NEW.id, v_task.id, 1, 'ALL')
        ON CONFLICT (user_id, task_id, period_key)
        DO UPDATE SET progress = 1, last_updated = NOW();
        
        UPDATE user_task_progress SET is_completed = true 
        WHERE user_id = NEW.id AND task_id = v_task.id AND period_key = 'ALL';
      END LOOP;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_user_update_mission ON users;
CREATE TRIGGER trigger_user_update_mission
AFTER UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION handle_user_update_mission_progress();

-- 9. Trigger for Marketplace Listing
CREATE OR REPLACE FUNCTION handle_listing_mission_progress()
RETURNS TRIGGER AS $$
DECLARE
  v_task RECORD;
BEGIN
  -- Listing created
  FOR v_task IN SELECT * FROM tasks WHERE condition_type = 'sell_item' AND type = 'achievement' AND is_active = true LOOP
    INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
    VALUES (NEW.seller_id, v_task.id, 1, 'ALL')
    ON CONFLICT (user_id, task_id, period_key)
    DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    
    UPDATE user_task_progress SET is_completed = true 
    WHERE user_id = NEW.seller_id AND task_id = v_task.id AND period_key = 'ALL' AND progress >= v_task.target_value AND is_completed = false;
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_listing_mission ON marketplace_listings;
CREATE TRIGGER trigger_listing_mission
AFTER INSERT ON marketplace_listings
FOR EACH ROW
EXECUTE FUNCTION handle_listing_mission_progress();

-- 10. RPC: Track Mission Event (Frontend triggers)
CREATE OR REPLACE FUNCTION track_mission_event(p_event_type TEXT, p_data JSONB DEFAULT '{}'::jsonb)
RETURNS JSONB AS $$
DECLARE
  v_user_id UUID;
  v_task RECORD;
  v_period_key TEXT;
  v_current_progress INT;
  v_meta JSONB;
  v_item_id TEXT;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Not authenticated');
  END IF;

  FOR v_task IN SELECT * FROM tasks WHERE condition_type = p_event_type AND is_active = true LOOP
    IF v_task.type = 'daily' THEN
      v_period_key := to_char(NOW(), 'YYYY-MM-DD');
    ELSIF v_task.type = 'weekly' THEN
      v_period_key := to_char(NOW(), 'IYYY-IW');
    ELSE
      v_period_key := 'ALL';
    END IF;

    IF p_event_type = 'view_product' THEN
      v_item_id := p_data->>'product_id';
      SELECT progress, metadata INTO v_current_progress, v_meta FROM user_task_progress 
      WHERE user_id = v_user_id AND task_id = v_task.id AND period_key = v_period_key;
      
      IF NOT FOUND THEN
        v_current_progress := 0;
        v_meta := '{"viewed_ids": []}'::jsonb;
      END IF;
      
      IF v_meta->'viewed_ids' ? v_item_id THEN
        CONTINUE; 
      END IF;
      
      v_meta := jsonb_set(v_meta, '{viewed_ids}', (v_meta->'viewed_ids') || to_jsonb(v_item_id));
      
      INSERT INTO user_task_progress (user_id, task_id, progress, period_key, metadata)
      VALUES (v_user_id, v_task.id, 1, v_period_key, v_meta)
      ON CONFLICT (user_id, task_id, period_key) 
      DO UPDATE SET progress = jsonb_array_length(v_meta->'viewed_ids'), metadata = v_meta, last_updated = NOW();
      
    ELSIF p_event_type = 'share_app' OR p_event_type = 'like_ranking' THEN
      INSERT INTO user_task_progress (user_id, task_id, progress, period_key)
      VALUES (v_user_id, v_task.id, 1, v_period_key)
      ON CONFLICT (user_id, task_id, period_key) 
      DO UPDATE SET progress = user_task_progress.progress + 1, last_updated = NOW();
    END IF;
    
    -- Check completion
    UPDATE user_task_progress 
    SET is_completed = true 
    WHERE user_id = v_user_id 
      AND task_id = v_task.id 
      AND period_key = v_period_key 
      AND progress >= v_task.target_value 
      AND is_completed = false;
      
  END LOOP;

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. Get User Missions Status (Frontend fetch)
DROP FUNCTION IF EXISTS get_user_missions();
CREATE OR REPLACE FUNCTION get_user_missions()
RETURNS TABLE (
  id UUID,
  type TEXT,
  title TEXT,
  description TEXT,
  target_value INTEGER,
  reward_coins INTEGER,
  condition_type TEXT,
  icon_name TEXT,
  progress INTEGER,
  is_completed BOOLEAN,
  is_claimed BOOLEAN,
  period_key TEXT
) AS $$
DECLARE
  v_user_id UUID;
  v_today TEXT := to_char(NOW(), 'YYYY-MM-DD');
  v_week TEXT := to_char(NOW(), 'IYYY-IW');
BEGIN
  v_user_id := auth.uid();
  
  RETURN QUERY
  SELECT 
    t.id,
    t.type,
    t.title,
    t.description,
    t.target_value,
    t.reward_coins,
    t.condition_type,
    t.icon_name,
    COALESCE(utp.progress, 0) as progress,
    COALESCE(utp.is_completed, false) as is_completed,
    COALESCE(utp.is_claimed, false) as is_claimed,
    COALESCE(utp.period_key, 
      CASE 
        WHEN t.type = 'daily' THEN v_today
        WHEN t.type = 'weekly' THEN v_week
        ELSE 'ALL'
      END
    ) as period_key
  FROM tasks t
  LEFT JOIN user_task_progress utp ON t.id = utp.task_id AND utp.user_id = v_user_id 
    AND (
      (t.type = 'daily' AND utp.period_key = v_today) OR
      (t.type = 'weekly' AND utp.period_key = v_week) OR
      (t.type = 'achievement' AND utp.period_key = 'ALL')
    )
  WHERE t.is_active = true
  ORDER BY 
    CASE WHEN COALESCE(utp.is_claimed, false) THEN 2 ELSE 0 END,
    CASE WHEN COALESCE(utp.is_completed, false) THEN 0 ELSE 1 END,
    t.type,
    t.reward_coins DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION get_user_missions() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION daily_check_in(uuid) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_check_in_status(uuid) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION claim_task_reward(uuid, text) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION get_cat_id(text) TO service_role, authenticated, anon;

-- 更新排行榜函數邏輯
-- 修正：先 DROP 舊函數以避免回傳型別衝突 (ERROR: 42P13)

-- 1. 歐皇榜 (Lucky): 大賞數量最多 (每週一更新)
DROP FUNCTION IF EXISTS get_leaderboard_lucky(text);

CREATE OR REPLACE FUNCTION get_leaderboard_lucky(p_range TEXT DEFAULT 'week')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  big_prize_count BIGINT,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    COUNT(*) as big_prize_count,
    RANK() OVER (ORDER BY COUNT(*) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    (
      CASE 
        -- Day: Yesterday
        WHEN p_range = 'day' THEN 
          d.created_at >= date_trunc('day', NOW() - INTERVAL '1 day') AND
          d.created_at < date_trunc('day', NOW())
          
        -- Week: Last Week
        WHEN p_range = 'week' THEN 
          d.created_at >= date_trunc('week', NOW() - INTERVAL '1 week') AND
          d.created_at < date_trunc('week', NOW())
          
        WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
        ELSE TRUE
      END
    )
    AND d.prize_level = ANY(p.major_prizes)
  GROUP BY u.id, u.name, au.raw_user_meta_data
  ORDER BY big_prize_count DESC
  LIMIT 10;
END;
$$;

-- 2. 非酋榜 (Unlucky): 大賞佔比最低 (每月一號更新)
DROP FUNCTION IF EXISTS get_leaderboard_unlucky(text);

CREATE OR REPLACE FUNCTION get_leaderboard_unlucky(p_range TEXT DEFAULT 'month')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  grand_prize_count BIGINT,
  total_draws BIGINT,
  grand_prize_rate NUMERIC,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    COUNT(*) FILTER (WHERE d.prize_level = ANY(p.major_prizes)) as grand_prize_count,
    COUNT(*) as total_draws,
    ROUND((COUNT(*) FILTER (WHERE d.prize_level = ANY(p.major_prizes))::numeric / NULLIF(COUNT(*), 0)) * 100, 2) as grand_prize_rate,
    RANK() OVER (ORDER BY (COUNT(*) FILTER (WHERE d.prize_level = ANY(p.major_prizes))::numeric / NULLIF(COUNT(*), 0)) ASC, COUNT(*) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    CASE 
      -- Day: Yesterday
      WHEN p_range = 'day' THEN 
        d.created_at >= date_trunc('day', NOW() - INTERVAL '1 day') AND
        d.created_at < date_trunc('day', NOW())
        
      -- Week: Last Week
      WHEN p_range = 'week' THEN 
        d.created_at >= date_trunc('week', NOW() - INTERVAL '1 week') AND
        d.created_at < date_trunc('week', NOW())
        
      WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
      ELSE TRUE
    END
  GROUP BY u.id, u.name, au.raw_user_meta_data
  HAVING COUNT(*) >= 10 -- 門檻：至少抽 10 次才列入計算
  ORDER BY grand_prize_rate ASC, total_draws DESC
  LIMIT 10;
END;
$$;

-- 3. 賞金榜 (Whales): 消耗代幣最多 (支援日榜)
DROP FUNCTION IF EXISTS get_leaderboard_whales(text);

CREATE OR REPLACE FUNCTION get_leaderboard_whales(p_range TEXT DEFAULT 'week')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  total_spent NUMERIC,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    SUM(p.price) as total_spent,
    RANK() OVER (ORDER BY SUM(p.price) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    CASE 
      -- Day: Yesterday
      WHEN p_range = 'day' THEN 
        d.created_at >= date_trunc('day', NOW() - INTERVAL '1 day') AND
        d.created_at < date_trunc('day', NOW())
        
      -- Week: Last Week
      WHEN p_range = 'week' THEN 
        d.created_at >= date_trunc('week', NOW() - INTERVAL '1 week') AND
        d.created_at < date_trunc('week', NOW())
        
      WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
      ELSE TRUE
    END
  GROUP BY u.id, u.name, au.raw_user_meta_data
  ORDER BY total_spent DESC
  LIMIT 10;
END;
$$;

-- ==========================================
-- COUPONS
-- ==========================================
INSERT INTO coupons (title, code, discount_type, discount_value, min_spend, is_active) VALUES
('超強折折折', 'SUPER50', 'fixed', 50, 0, true),
('新人禮包', 'NEWUSER', 'percentage', 10, 100, true);

-- Assign coupons to all existing users
INSERT INTO user_coupons (user_id, coupon_id, status)
SELECT u.id, c.id, 'unused'
FROM users u
CROSS JOIN coupons c
WHERE NOT EXISTS (
  SELECT 1 FROM user_coupons uc 
  WHERE uc.user_id = u.id AND uc.coupon_id = c.id
);

-- ==========================================
-- WORSHIP PLAYER RPC (Update Reward to 10 Points)
-- ==========================================
CREATE OR REPLACE FUNCTION worship_player(p_target_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_today DATE := CURRENT_DATE;
  v_already_worshipped BOOLEAN;
BEGIN
  -- 取得當前用戶
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', '請先登入');
  END IF;

  -- 不能膜拜自己
  IF v_user_id = p_target_id THEN
    RETURN jsonb_build_object('success', false, 'message', '不能膜拜自己');
  END IF;

  -- 檢查今日是否已膜拜 (利用 worship_date 查詢)
  SELECT EXISTS (
    SELECT 1 FROM worship_logs 
    WHERE worshipper_id = v_user_id 
    AND worship_date = v_today
  ) INTO v_already_worshipped;

  IF v_already_worshipped THEN
    RETURN jsonb_build_object('success', false, 'message', '今天已經膜拜過大佬了，明天再來吧！');
  END IF;

  -- 寫入紀錄 (明確寫入 worship_date)
  INSERT INTO worship_logs (worshipper_id, target_id, worship_date)
  VALUES (v_user_id, p_target_id, v_today);

  -- 給予獎勵 (10 積分)
  UPDATE users
  SET points = points + 10
  WHERE id = v_user_id;

  RETURN jsonb_build_object('success', true, 'message', '膜拜成功！獲得 10 積分');
EXCEPTION WHEN unique_violation THEN
  RETURN jsonb_build_object('success', false, 'message', '今天已經膜拜過了');
WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'message', SQLERRM);
END;
$$;
