-- 1. Create Daily Check-in Table
CREATE TABLE IF NOT EXISTS daily_check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    check_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    reward_amount INTEGER DEFAULT 10,
    CONSTRAINT unique_daily_check_in UNIQUE (user_id, check_in_date)
);

ALTER TABLE daily_check_ins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own check-ins" ON daily_check_ins;
CREATE POLICY "Users can view own check-ins" ON daily_check_ins FOR SELECT USING (auth.uid() = user_id);

-- 2. Function: Get Check-in Status
CREATE OR REPLACE FUNCTION get_check_in_status(p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_streak INTEGER := 0;
    v_checked_in_today BOOLEAN := false;
    v_today DATE := CURRENT_DATE;
    v_check_date DATE;
BEGIN
    -- Check today
    SELECT EXISTS(SELECT 1 FROM daily_check_ins WHERE user_id = p_user_id AND check_in_date = v_today)
    INTO v_checked_in_today;

    -- Calculate streak
    v_check_date := v_today;
    IF NOT v_checked_in_today THEN
        v_check_date := v_today - 1;
    END IF;

    LOOP
        PERFORM 1 FROM daily_check_ins WHERE user_id = p_user_id AND check_in_date = v_check_date;
        IF FOUND THEN
            v_streak := v_streak + 1;
            v_check_date := v_check_date - 1;
        ELSE
            EXIT;
        END IF;
    END LOOP;

    RETURN jsonb_build_object(
        'consecutive_days', v_streak,
        'checked_in_today', v_checked_in_today,
        'next_reward', 10 + (v_streak % 7) * 5
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Function: Daily Check-in
CREATE OR REPLACE FUNCTION daily_check_in(p_user_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_streak INTEGER;
    v_reward INTEGER;
    v_today DATE := CURRENT_DATE;
BEGIN
    IF EXISTS(SELECT 1 FROM daily_check_ins WHERE user_id = p_user_id AND check_in_date = v_today) THEN
        RETURN jsonb_build_object('success', false, 'message', '今日已簽到');
    END IF;

    -- Calculate streak (from yesterday)
    DECLARE
        v_check_date DATE := v_today - 1;
        v_temp_streak INTEGER := 0;
    BEGIN
        LOOP
            PERFORM 1 FROM daily_check_ins WHERE user_id = p_user_id AND check_in_date = v_check_date;
            IF FOUND THEN
                v_temp_streak := v_temp_streak + 1;
                v_check_date := v_check_date - 1;
            ELSE
                EXIT;
            END IF;
        END LOOP;
        v_streak := v_temp_streak;
    END;

    v_reward := 10 + (v_streak % 7) * 5;

    INSERT INTO daily_check_ins (user_id, check_in_date, reward_amount)
    VALUES (p_user_id, v_today, v_reward);

    -- Update users tokens
    UPDATE users SET tokens = COALESCE(tokens, 0) + v_reward WHERE id = p_user_id;

    RETURN jsonb_build_object(
        'success', true, 
        'reward', v_reward,
        'streak', v_streak + 1
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Ensure Tasks Table Exists and Seed Data
-- (Assuming tasks table created by previous SQL, if not, create it here)
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('daily', 'weekly', 'achievement')),
  title TEXT NOT NULL,
  description TEXT,
  target_value INTEGER NOT NULL DEFAULT 1,
  reward_coins INTEGER NOT NULL DEFAULT 0,
  condition_type TEXT NOT NULL CHECK (condition_type IN ('login', 'draw_count', 'spend_amount', 'share_app')),
  icon_name TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Tasks (Upsert based on title/type to avoid duplicates if possible, but UUID is random)
-- We'll just insert if table is empty for simplicity
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tasks) THEN
        INSERT INTO tasks (type, title, description, target_value, reward_coins, condition_type, icon_name) VALUES
        ('daily', '每日首抽', '完成每日第一次抽獎', 1, 50, 'draw_count', 'Ticket'),
        ('daily', '分享應用', '分享連結給朋友', 1, 30, 'share_app', 'Share'),
        ('weekly', '每週十抽', '本週累積進行 10 次抽獎', 10, 200, 'draw_count', 'Layers'),
        ('achievement', '抽獎達人', '累積進行 100 次抽獎', 100, 1000, 'draw_count', 'Trophy');
    END IF;
END $$;

-- 5. Function: Get User Missions (Ensure it exists)
CREATE OR REPLACE FUNCTION get_user_missions()
RETURNS TABLE (
  id UUID,
  type TEXT,
  title TEXT,
  description TEXT,
  target_value INTEGER,
  reward_coins INTEGER,
  condition_type TEXT,
  icon_name TEXT,
  progress INTEGER,
  is_completed BOOLEAN,
  is_claimed BOOLEAN,
  period_key TEXT
) AS $$
DECLARE
  v_user_id UUID;
  v_today TEXT;
  v_week TEXT;
BEGIN
  v_user_id := auth.uid();
  v_today := to_char(NOW(), 'YYYY-MM-DD');
  v_week := to_char(NOW(), 'IYYY-IW');

  RETURN QUERY
  SELECT 
    t.id,
    t.type,
    t.title,
    t.description,
    t.target_value,
    t.reward_coins,
    t.condition_type,
    t.icon_name,
    COALESCE(utp.progress, 0) as progress,
    COALESCE(utp.is_completed, false) as is_completed,
    COALESCE(utp.is_claimed, false) as is_claimed,
    COALESCE(utp.period_key, 
      CASE 
        WHEN t.type = 'daily' THEN v_today
        WHEN t.type = 'weekly' THEN v_week
        ELSE 'ALL'
      END
    ) as period_key
  FROM tasks t
  LEFT JOIN user_task_progress utp ON t.id = utp.task_id AND utp.user_id = v_user_id 
    AND (
      (t.type = 'daily' AND utp.period_key = v_today) OR
      (t.type = 'weekly' AND utp.period_key = v_week) OR
      (t.type = 'achievement' AND utp.period_key = 'ALL')
    )
  WHERE t.is_active = true
  ORDER BY 
    CASE WHEN COALESCE(utp.is_claimed, false) THEN 2 ELSE 0 END,
    CASE WHEN COALESCE(utp.is_completed, false) THEN 0 ELSE 1 END,
    t.type,
    t.reward_coins DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
