-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users Table (Updated to match Supabase Auth)
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  -- user_id removed as id is now the UUID
  name TEXT,
  email TEXT UNIQUE NOT NULL,
  -- password removed as auth is handled by Supabase Auth
  phone TEXT,
  tokens INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user',
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  total_draws INTEGER DEFAULT 0,
  total_spent DECIMAL(10, 2) DEFAULT 0,
  address TEXT,
  recipient_name TEXT,
  recipient_phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_login_at TIMESTAMP WITH TIME ZONE
);

-- Trigger to automatically create public.users entry when auth.users is created
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'name', new.email));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists to avoid errors on repeated runs
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Categories Table
DROP TABLE IF EXISTS categories CASCADE;
CREATE TABLE categories (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Products Table (New)
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  category_id UUID REFERENCES categories(id),
  price DECIMAL(10, 2) NOT NULL,
  remaining INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'pending', 'ended')),
  sales INTEGER DEFAULT 0,
  is_hot BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  started_at TIMESTAMP WITH TIME ZONE,
  ended_at TIMESTAMP WITH TIME ZONE,
  txid_hash VARCHAR(255),
  seed VARCHAR(255),
  image_url TEXT,
  release_year VARCHAR(10),
  release_month VARCHAR(10),
  distributor VARCHAR(100),
  rarity INTEGER,
  total_count INTEGER,
  major_prizes TEXT[] DEFAULT ARRAY['A賞']
);

-- Product Prizes Table (New)
DROP TABLE IF EXISTS product_prizes CASCADE;
CREATE TABLE product_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  level VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  image_url TEXT,
  total INTEGER NOT NULL,
  remaining INTEGER NOT NULL,
  probability DECIMAL(5, 2) NOT NULL,
  recycle_value INTEGER DEFAULT 0
);

-- Orders Table (New)
DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  recipient_name VARCHAR(100),
  recipient_phone VARCHAR(50),
  address TEXT,
  status VARCHAR(20) NOT NULL CHECK (status IN ('submitted', 'processing', 'picked_up', 'shipping', 'delivered', 'cancelled')),
  tracking_number VARCHAR(100),
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  shipped_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order Items Table (New)
DROP TABLE IF EXISTS order_items CASCADE;
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_name VARCHAR(255),
  prize_name VARCHAR(255),
  prize_level VARCHAR(50),
  image_url TEXT,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER DEFAULT 1
);

-- Draw Records Table (New)
DROP TABLE IF EXISTS draw_records CASCADE;
CREATE TABLE draw_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  ticket_number INTEGER NOT NULL,
  prize_level VARCHAR(50) NOT NULL,
  prize_name VARCHAR(255) NOT NULL,
  txid_seed VARCHAR(255) NOT NULL,
  txid_nonce INTEGER NOT NULL,
  txid_hash VARCHAR(255) NOT NULL,
  random_value DECIMAL(20, 18) NOT NULL,
  profit_rate DECIMAL(5, 2) DEFAULT 1.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Recharge Records Table
DROP TABLE IF EXISTS recharge_records CASCADE;
CREATE TABLE recharge_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  amount DECIMAL(10, 2) NOT NULL,
  bonus DECIMAL(10, 2) DEFAULT 0,
  status VARCHAR(20) NOT NULL CHECK (status IN ('success', 'pending', 'failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
