-- Roles Table
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL, -- e.g., 'super_admin'
  display_name VARCHAR(100) NOT NULL, -- e.g., '超級管理員'
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Permissions Table (Optional, or just store permissions as JSONB/Array in roles)
-- Storing as JSONB or Array in roles is easier for simple apps.
-- Let's stick to a simple JSONB column in roles for now to avoid complexity, or a separate table if we want strict normalization.
-- Given the requirement "checkboxes for pages", a simple text array or JSON column in roles table is sufficient.

ALTER TABLE roles ADD COLUMN IF NOT EXISTS permissions TEXT[] DEFAULT '{}';

-- Admins Table
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert Default Roles
INSERT INTO roles (name, display_name, description, permissions) VALUES
('super_admin', '超級管理員', '擁有系統所有權限', ARRAY['all']),
('admin', '管理員', '一般管理權限，無法管理其他管理員', ARRAY['dashboard_view', 'products_manage', 'orders_manage', 'users_manage', 'draws_view', 'recharges_view']),
('operator', '營運人員', '負責日常營運與訂單處理', ARRAY['dashboard_view', 'orders_manage', 'draws_view']),
('marketing', '行銷人員', '負責行銷活動與數據查看', ARRAY['dashboard_view', 'products_manage']),
('logistics', '物流人員', '負責出貨與配送管理', ARRAY['orders_manage'])
ON CONFLICT (name) DO NOTHING;

-- Insert Initial Admin (Password: superadmin123)
INSERT INTO admins (username, email, password_hash, role_id, status)
SELECT 'superadmin', 'admin@example.com', 'superadmin123', id, 'active'
FROM roles WHERE name = 'super_admin'
ON CONFLICT (username) DO NOTHING;
