-- Create draw_records table
CREATE TABLE IF NOT EXISTS draw_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(user_id),
    product_id BIGINT REFERENCES products(id),
    prize_level VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    txid_nonce BIGINT,
    ticket_number INTEGER,
    txid_hash TEXT,
    status VARCHAR(50) DEFAULT 'success',
    profit_rate NUMERIC(5, 2) DEFAULT 1.0,
    random_value NUMERIC
);

-- Create recharge_records table
CREATE TABLE IF NOT EXISTS recharge_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(100),
    user_id UUID REFERENCES users(user_id),
    amount NUMERIC(10, 2),
    bonus NUMERIC(10, 2) DEFAULT 0,
    status VARCHAR(50) CHECK (status IN ('success', 'pending', 'failed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
