
-- Create action_logs table
CREATE TABLE IF NOT EXISTS action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50),
    action VARCHAR(50) NOT NULL,
    target VARCHAR(100),
    details TEXT,
    ip VARCHAR(50),
    status VARCHAR(20) DEFAULT 'success',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_action_logs_created_at ON action_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_logs_admin_id ON action_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_action_logs_action ON action_logs(action);

-- Add RLS policies
ALTER TABLE action_logs ENABLE ROW LEVEL SECURITY;

-- Allow admins to insert logs
CREATE POLICY "Admins can insert logs" ON action_logs
    FOR INSERT
    TO public
    WITH CHECK (true); -- Ideally restrict to authenticated admins, but for now allow public insert from client if needed, or better relying on middleware protection.
    -- Since we don't have Supabase Auth for admins yet (using custom table), we might need to allow public insert or use a service key in API. 
    -- But since we are using client-side supabase client, we need RLS.
    -- If we use 'anon' key, we need policy for anon.
    -- For now, allow insert for everyone (or restrict by IP/header if possible, but difficult with just RLS).
    -- Realistically, we should check if the user is an admin. But we don't have auth.users linked.
    -- So we'll trust the client for now (prototype phase).

-- Allow admins to view logs
CREATE POLICY "Admins can view logs" ON action_logs
    FOR SELECT
    TO public
    USING (true);
