-- Unify Inventory Schema

-- 1. Ensure orders table exists
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  recipient_name VARCHAR(100),
  recipient_phone VARCHAR(50),
  address TEXT,
  status VARCHAR(20) NOT NULL CHECK (status IN ('submitted', 'processing', 'picked_up', 'shipping', 'delivered', 'cancelled')),
  tracking_number VARCHAR(100),
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  shipped_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add inventory fields to draw_records
ALTER TABLE draw_records 
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'in_warehouse' CHECK (status IN ('in_warehouse', 'pending_delivery', 'shipped', 'exchanged')),
ADD COLUMN IF NOT EXISTS order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS product_prize_id BIGINT REFERENCES product_prizes(id) ON DELETE SET NULL;

-- 3. Add RLS policies for orders
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own orders" ON orders;
CREATE POLICY "Users can view their own orders" ON orders
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own orders" ON orders;
CREATE POLICY "Users can insert their own orders" ON orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. Add RLS policies for draw_records updates
DROP POLICY IF EXISTS "Users can update their own draw records" ON draw_records;
CREATE POLICY "Users can update their own draw records" ON draw_records
  FOR UPDATE USING (auth.uid() = user_id);
