-- 1. 建立膜拜紀錄表 (Worship Logs)
-- 修改：增加 worship_date 欄位以避免 Index Expression Immutable 問題
CREATE TABLE IF NOT EXISTS worship_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worshipper_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  worship_date DATE NOT NULL DEFAULT CURRENT_DATE
);

-- 添加唯一約束：同一位玩家每天只能膜拜一次 (Global Limit)
-- 直接對 worship_date 欄位建立索引，避免函數索引的 immutable 問題
CREATE UNIQUE INDEX IF NOT EXISTS idx_worship_daily_limit ON worship_logs (worshipper_id, worship_date);

-- 2. 膜拜 RPC (Worship Player)
CREATE OR REPLACE FUNCTION worship_player(p_target_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_today DATE := CURRENT_DATE;
  v_already_worshipped BOOLEAN;
BEGIN
  -- 取得當前用戶
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', '請先登入');
  END IF;

  -- 不能膜拜自己
  IF v_user_id = p_target_id THEN
    RETURN jsonb_build_object('success', false, 'message', '不能膜拜自己');
  END IF;

  -- 檢查今日是否已膜拜 (利用 worship_date 查詢)
  SELECT EXISTS (
    SELECT 1 FROM worship_logs 
    WHERE worshipper_id = v_user_id 
    AND worship_date = v_today
  ) INTO v_already_worshipped;

  IF v_already_worshipped THEN
    RETURN jsonb_build_object('success', false, 'message', '今天已經膜拜過大佬了，明天再來吧！');
  END IF;

  -- 寫入紀錄 (明確寫入 worship_date)
  INSERT INTO worship_logs (worshipper_id, target_id, worship_date)
  VALUES (v_user_id, p_target_id, v_today);

  -- 給予獎勵 (1枚代幣)
  UPDATE users
  SET tokens = tokens + 1
  WHERE id = v_user_id;

  RETURN jsonb_build_object('success', true, 'message', '膜拜成功！獲得 1 枚代幣');
EXCEPTION WHEN unique_violation THEN
  RETURN jsonb_build_object('success', false, 'message', '今天已經膜拜過了');
WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'message', SQLERRM);
END;
$$;

-- 3. 排行榜 RPCs

-- 賞金榜 (Whales): 消耗代幣最多
CREATE OR REPLACE FUNCTION get_leaderboard_whales(p_range TEXT DEFAULT 'week')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  total_spent NUMERIC,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    SUM(p.price) as total_spent,
    RANK() OVER (ORDER BY SUM(p.price) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    CASE 
      WHEN p_range = 'week' THEN d.created_at >= date_trunc('week', NOW())
      WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
      ELSE TRUE -- all time
    END
  GROUP BY u.id, u.name, au.raw_user_meta_data
  ORDER BY total_spent DESC
  LIMIT 10;
END;
$$;

-- 歐皇榜 (Lucky): 大賞數量最多
CREATE OR REPLACE FUNCTION get_leaderboard_lucky(p_range TEXT DEFAULT 'week')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  big_prize_count BIGINT,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    COUNT(*) as big_prize_count,
    RANK() OVER (ORDER BY COUNT(*) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    (
      CASE 
        WHEN p_range = 'week' THEN d.created_at >= date_trunc('week', NOW())
        WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
        ELSE TRUE
      END
    )
    -- 判斷大賞：當 prize_level 存在於該商品的 major_prizes 陣列中
    AND d.prize_level = ANY(p.major_prizes)
  GROUP BY u.id, u.name, au.raw_user_meta_data
  ORDER BY big_prize_count DESC
  LIMIT 10;
END;
$$;

-- 非酋榜 (Unlucky): 小賞佔比最高 (至少抽過 10 次)
CREATE OR REPLACE FUNCTION get_leaderboard_unlucky(p_range TEXT DEFAULT 'week')
RETURNS TABLE (
  user_id UUID,
  nickname TEXT,
  avatar_url TEXT,
  small_prize_count BIGINT,
  total_draws BIGINT,
  unlucky_rate NUMERIC,
  rank BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    u.id, 
    COALESCE(u.name, '神秘玩家') as nickname, 
    (au.raw_user_meta_data->>'avatar_url')::TEXT as avatar_url,
    -- 小賞數量
    COUNT(*) FILTER (WHERE NOT (d.prize_level = ANY(p.major_prizes))) as small_prize_count,
    -- 總抽數
    COUNT(*) as total_draws,
    -- 非酋率
    ROUND((COUNT(*) FILTER (WHERE NOT (d.prize_level = ANY(p.major_prizes)))::numeric / NULLIF(COUNT(*), 0)) * 100, 2) as unlucky_rate,
    RANK() OVER (ORDER BY (COUNT(*) FILTER (WHERE NOT (d.prize_level = ANY(p.major_prizes)))::numeric / NULLIF(COUNT(*), 0)) DESC) as rank
  FROM draw_records d
  JOIN products p ON d.product_id = p.id
  JOIN users u ON d.user_id = u.id
  JOIN auth.users au ON u.id = au.id
  WHERE 
    CASE 
      WHEN p_range = 'week' THEN d.created_at >= date_trunc('week', NOW())
      WHEN p_range = 'month' THEN d.created_at >= date_trunc('month', NOW())
      ELSE TRUE
    END
  GROUP BY u.id, u.name, au.raw_user_meta_data
  HAVING COUNT(*) >= 10 -- 門檻：至少抽 10 次才列入計算
  ORDER BY unlucky_rate DESC, total_draws DESC
  LIMIT 10;
END;
$$;
