CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS exchange_offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'deleted')),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS exchange_offers_owner_id_idx ON exchange_offers (owner_id);
CREATE INDEX IF NOT EXISTS exchange_offers_status_created_at_idx ON exchange_offers (status, created_at DESC);

CREATE TABLE IF NOT EXISTS exchange_offer_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id UUID NOT NULL REFERENCES exchange_offers(id) ON DELETE CASCADE,
  side TEXT NOT NULL CHECK (side IN ('want', 'give')),
  external_id TEXT NOT NULL,
  name TEXT NOT NULL,
  series TEXT,
  image_url TEXT,
  value INTEGER NOT NULL DEFAULT 0,
  position SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (offer_id, side, position)
);

CREATE INDEX IF NOT EXISTS exchange_offer_cards_offer_id_idx ON exchange_offer_cards (offer_id);

CREATE TABLE IF NOT EXISTS exchange_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  offer_id UUID NOT NULL REFERENCES exchange_offers(id) ON DELETE CASCADE,
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  initiator_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  step SMALLINT NOT NULL DEFAULT 1 CHECK (step IN (1, 2, 3, 4, 5)),
  confirmations JSONB NOT NULL DEFAULT '{}'::jsonb,
  recipient JSONB,
  tracking_number TEXT,
  receipt_media JSONB,
  receipt_note TEXT,
  receipt_action TEXT CHECK (receipt_action IN ('none', 'return')),
  rating_stars SMALLINT CHECK (rating_stars BETWEEN 1 AND 5),
  rating_comment TEXT,
  rating_submitted BOOLEAN NOT NULL DEFAULT FALSE,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS exchange_orders_offer_id_idx ON exchange_orders (offer_id);
CREATE INDEX IF NOT EXISTS exchange_orders_owner_id_updated_at_idx ON exchange_orders (owner_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS exchange_orders_initiator_id_updated_at_idx ON exchange_orders (initiator_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS exchange_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id UUID NOT NULL REFERENCES exchange_offers(id) ON DELETE CASCADE,
  order_id UUID REFERENCES exchange_orders(id) ON DELETE SET NULL,
  sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'text' CHECK (kind IN ('text', 'system')),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS exchange_messages_offer_id_created_at_idx ON exchange_messages (offer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS exchange_messages_sender_id_created_at_idx ON exchange_messages (sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS exchange_messages_receiver_id_created_at_idx ON exchange_messages (receiver_id, created_at DESC);

ALTER TABLE exchange_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE exchange_offer_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE exchange_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE exchange_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Exchange offers: public can view active, owner can view all" ON exchange_offers;
CREATE POLICY "Exchange offers: public can view active, owner can view all"
  ON exchange_offers FOR SELECT
  USING (status = 'active' OR auth.uid() = owner_id);

DROP POLICY IF EXISTS "Exchange offers: owner can insert" ON exchange_offers;
CREATE POLICY "Exchange offers: owner can insert"
  ON exchange_offers FOR INSERT
  WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Exchange offers: owner can update" ON exchange_offers;
CREATE POLICY "Exchange offers: owner can update"
  ON exchange_offers FOR UPDATE
  USING (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Exchange offers: owner can delete" ON exchange_offers;
CREATE POLICY "Exchange offers: owner can delete"
  ON exchange_offers FOR DELETE
  USING (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Exchange offer cards: view follows offer visibility" ON exchange_offer_cards;
CREATE POLICY "Exchange offer cards: view follows offer visibility"
  ON exchange_offer_cards FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_offer_cards.offer_id
        AND (o.status = 'active' OR auth.uid() = o.owner_id)
    )
  );

DROP POLICY IF EXISTS "Exchange offer cards: owner can insert" ON exchange_offer_cards;
CREATE POLICY "Exchange offer cards: owner can insert"
  ON exchange_offer_cards FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_offer_cards.offer_id
        AND auth.uid() = o.owner_id
    )
  );

DROP POLICY IF EXISTS "Exchange offer cards: owner can update" ON exchange_offer_cards;
CREATE POLICY "Exchange offer cards: owner can update"
  ON exchange_offer_cards FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_offer_cards.offer_id
        AND auth.uid() = o.owner_id
    )
  );

DROP POLICY IF EXISTS "Exchange offer cards: owner can delete" ON exchange_offer_cards;
CREATE POLICY "Exchange offer cards: owner can delete"
  ON exchange_offer_cards FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_offer_cards.offer_id
        AND auth.uid() = o.owner_id
    )
  );

DROP POLICY IF EXISTS "Exchange orders: participants can view" ON exchange_orders;
CREATE POLICY "Exchange orders: participants can view"
  ON exchange_orders FOR SELECT
  USING (auth.uid() = owner_id OR auth.uid() = initiator_id);

DROP POLICY IF EXISTS "Exchange orders: initiator can insert" ON exchange_orders;
CREATE POLICY "Exchange orders: initiator can insert"
  ON exchange_orders FOR INSERT
  WITH CHECK (
    auth.uid() = initiator_id
    AND initiator_id <> owner_id
    AND EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_orders.offer_id
        AND o.status = 'active'
        AND o.owner_id = exchange_orders.owner_id
    )
  );

DROP POLICY IF EXISTS "Exchange orders: participants can update" ON exchange_orders;
CREATE POLICY "Exchange orders: participants can update"
  ON exchange_orders FOR UPDATE
  USING (auth.uid() = owner_id OR auth.uid() = initiator_id);

DROP POLICY IF EXISTS "Exchange orders: participants can delete" ON exchange_orders;
CREATE POLICY "Exchange orders: participants can delete"
  ON exchange_orders FOR DELETE
  USING (auth.uid() = owner_id OR auth.uid() = initiator_id);

DROP POLICY IF EXISTS "Exchange messages: participants can view" ON exchange_messages;
CREATE POLICY "Exchange messages: participants can view"
  ON exchange_messages FOR SELECT
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

DROP POLICY IF EXISTS "Exchange messages: sender can insert with offer owner involvement" ON exchange_messages;
CREATE POLICY "Exchange messages: sender can insert with offer owner involvement"
  ON exchange_messages FOR INSERT
  WITH CHECK (
    auth.uid() = sender_id
    AND sender_id <> receiver_id
    AND EXISTS (
      SELECT 1
      FROM exchange_offers o
      WHERE o.id = exchange_messages.offer_id
        AND (o.owner_id = sender_id OR o.owner_id = receiver_id)
    )
  );

DROP POLICY IF EXISTS "Exchange messages: sender can delete" ON exchange_messages;
CREATE POLICY "Exchange messages: sender can delete"
  ON exchange_messages FOR DELETE
  USING (auth.uid() = sender_id);

CREATE OR REPLACE FUNCTION public.get_user_displays(p_ids uuid[])
RETURNS TABLE(id uuid, name text, avatar_url text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    pid.id,
    COALESCE(NULLIF(u.name, ''), NULLIF(split_part(au.email, '@', 1), ''), 'user') as name,
    COALESCE(NULLIF(au.raw_user_meta_data->>'avatar_url', ''), '/images/avatar.png') as avatar_url
  FROM unnest(p_ids) as pid(id)
  LEFT JOIN public.users u ON u.id = pid.id
  LEFT JOIN auth.users au ON au.id = pid.id;
$$;

REVOKE ALL ON FUNCTION public.get_user_displays(uuid[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_user_displays(uuid[]) TO anon, authenticated;
