BEGIN;

CREATE TABLE IF NOT EXISTS public.marketplace_seller_profiles (
  seller_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  transfer_bank TEXT,
  transfer_account TEXT,
  transfer_name TEXT,
  private_trade_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.marketplace_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES public.marketplace_listings(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES public.users(id),
  buyer_id UUID NOT NULL REFERENCES public.users(id),
  item_index INTEGER NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price INTEGER NOT NULL CHECK (unit_price > 0),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('transfer','private')) DEFAULT 'transfer',
  step INTEGER NOT NULL DEFAULT 1 CHECK (step BETWEEN 1 AND 6),
  cancelled BOOLEAN NOT NULL DEFAULT false,
  cancel_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.marketplace_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES public.marketplace_listings(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.users(id),
  receiver_id UUID NOT NULL REFERENCES public.users(id),
  kind TEXT NOT NULL DEFAULT 'text' CHECK (kind IN ('text','system')),
  body TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.marketplace_seller_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Marketplace seller profiles - seller manage" ON public.marketplace_seller_profiles;
CREATE POLICY "Marketplace seller profiles - seller manage"
  ON public.marketplace_seller_profiles
  FOR ALL
  USING (seller_id = auth.uid())
  WITH CHECK (seller_id = auth.uid());

DROP POLICY IF EXISTS "Marketplace seller profiles - buyer view via order" ON public.marketplace_seller_profiles;
CREATE POLICY "Marketplace seller profiles - buyer view via order"
  ON public.marketplace_seller_profiles
  FOR SELECT
  USING (
    seller_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.marketplace_orders o
      WHERE o.seller_id = marketplace_seller_profiles.seller_id
        AND o.buyer_id = auth.uid()
        AND o.cancelled = false
    )
  );

DROP POLICY IF EXISTS "Marketplace orders - participants view" ON public.marketplace_orders;
CREATE POLICY "Marketplace orders - participants view"
  ON public.marketplace_orders
  FOR SELECT
  USING (buyer_id = auth.uid() OR seller_id = auth.uid());

DROP POLICY IF EXISTS "Marketplace orders - buyer create" ON public.marketplace_orders;
CREATE POLICY "Marketplace orders - buyer create"
  ON public.marketplace_orders
  FOR INSERT
  WITH CHECK (buyer_id = auth.uid());

DROP POLICY IF EXISTS "Marketplace orders - participants update" ON public.marketplace_orders;
CREATE POLICY "Marketplace orders - participants update"
  ON public.marketplace_orders
  FOR UPDATE
  USING (buyer_id = auth.uid() OR seller_id = auth.uid());

DROP POLICY IF EXISTS "Marketplace messages - participants view" ON public.marketplace_messages;
CREATE POLICY "Marketplace messages - participants view"
  ON public.marketplace_messages
  FOR SELECT
  USING (sender_id = auth.uid() OR receiver_id = auth.uid());

DROP POLICY IF EXISTS "Marketplace messages - send" ON public.marketplace_messages;
CREATE POLICY "Marketplace messages - send"
  ON public.marketplace_messages
  FOR INSERT
  WITH CHECK (
    sender_id = auth.uid()
    AND sender_id <> receiver_id
    AND EXISTS (
      SELECT 1 FROM public.marketplace_listings l
      WHERE l.id = marketplace_messages.listing_id
        AND (receiver_id = l.seller_id OR sender_id = l.seller_id)
    )
  );

CREATE OR REPLACE FUNCTION public.create_marketplace_order(
  p_listing_id BIGINT,
  p_item_index INTEGER,
  p_quantity INTEGER,
  p_payment_method TEXT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_buyer_id UUID;
  v_listing RECORD;
  v_items JSONB;
  v_item JSONB;
  v_len INTEGER;
  v_available INTEGER;
  v_new_qty INTEGER;
  v_unit_price INTEGER;
  v_method TEXT;
  v_order_id BIGINT;
  v_all_sold BOOLEAN;
BEGIN
  v_buyer_id := auth.uid();
  IF v_buyer_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'login_required');
  END IF;

  IF p_quantity IS NULL OR p_quantity < 1 THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid_quantity');
  END IF;

  v_method := COALESCE(NULLIF(p_payment_method, ''), 'transfer');
  IF v_method NOT IN ('transfer','private') THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid_payment_method');
  END IF;

  SELECT * INTO v_listing
  FROM public.marketplace_listings
  WHERE id = p_listing_id AND status = 'active'
  FOR UPDATE;

  IF v_listing IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'listing_not_found');
  END IF;

  IF v_listing.seller_id = v_buyer_id THEN
    RETURN jsonb_build_object('success', false, 'message', 'cannot_buy_own_listing');
  END IF;

  v_items := COALESCE(v_listing.items, '[]'::jsonb);
  IF jsonb_typeof(v_items) <> 'array' THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid_items');
  END IF;

  v_len := jsonb_array_length(v_items);
  IF p_item_index IS NULL OR p_item_index < 0 OR p_item_index >= v_len THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid_item');
  END IF;

  v_item := v_items -> p_item_index;
  v_available := COALESCE(NULLIF((v_item ->> 'quantity'), '')::int, 0);
  IF v_available < p_quantity THEN
    RETURN jsonb_build_object('success', false, 'message', 'insufficient_stock');
  END IF;

  v_unit_price := COALESCE(v_listing.price, 0);
  IF v_unit_price <= 0 THEN
    RETURN jsonb_build_object('success', false, 'message', 'invalid_price');
  END IF;

  v_new_qty := v_available - p_quantity;
  v_items := jsonb_set(v_items, ARRAY[p_item_index::text, 'quantity'], to_jsonb(v_new_qty), true);

  UPDATE public.marketplace_listings
  SET items = v_items, updated_at = NOW()
  WHERE id = p_listing_id;

  SELECT NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_items) AS e
    WHERE COALESCE(NULLIF((e->>'quantity'), '')::int, 0) > 0
  ) INTO v_all_sold;

  IF v_all_sold THEN
    UPDATE public.marketplace_listings
    SET status = 'sold', updated_at = NOW()
    WHERE id = p_listing_id;
  END IF;

  INSERT INTO public.marketplace_orders (
    listing_id, seller_id, buyer_id, item_index, quantity, unit_price, payment_method, step, cancelled
  ) VALUES (
    p_listing_id, v_listing.seller_id, v_buyer_id, p_item_index, p_quantity, v_unit_price, v_method, 1, false
  ) RETURNING id INTO v_order_id;

  INSERT INTO public.marketplace_messages (listing_id, sender_id, receiver_id, kind, body)
  VALUES (p_listing_id, v_buyer_id, v_listing.seller_id, 'system', '已建立訂單');

  RETURN jsonb_build_object('success', true, 'order_id', v_order_id);
END;
$$;

ALTER FUNCTION public.create_marketplace_order(BIGINT, INTEGER, INTEGER, TEXT) SET row_security = off;

CREATE OR REPLACE FUNCTION public.cancel_marketplace_order(
  p_order_id BIGINT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID;
  v_order RECORD;
  v_listing RECORD;
  v_items JSONB;
  v_item JSONB;
  v_available INTEGER;
  v_new_qty INTEGER;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'login_required');
  END IF;

  SELECT * INTO v_order
  FROM public.marketplace_orders
  WHERE id = p_order_id
  FOR UPDATE;

  IF v_order IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'order_not_found');
  END IF;

  IF v_order.cancelled THEN
    RETURN jsonb_build_object('success', true, 'message', 'already_cancelled');
  END IF;

  IF v_order.step <> 1 THEN
    RETURN jsonb_build_object('success', false, 'message', 'cannot_cancel');
  END IF;

  IF v_order.buyer_id <> v_uid AND v_order.seller_id <> v_uid THEN
    RETURN jsonb_build_object('success', false, 'message', 'forbidden');
  END IF;

  SELECT * INTO v_listing
  FROM public.marketplace_listings
  WHERE id = v_order.listing_id
  FOR UPDATE;

  v_items := COALESCE(v_listing.items, '[]'::jsonb);
  v_item := v_items -> v_order.item_index;
  v_available := COALESCE(NULLIF((v_item ->> 'quantity'), '')::int, 0);
  v_new_qty := v_available + v_order.quantity;
  v_items := jsonb_set(v_items, ARRAY[v_order.item_index::text, 'quantity'], to_jsonb(v_new_qty), true);

  UPDATE public.marketplace_listings
  SET items = v_items, status = 'active', updated_at = NOW()
  WHERE id = v_listing.id;

  UPDATE public.marketplace_orders
  SET cancelled = true, cancel_reason = 'cancelled', updated_at = NOW()
  WHERE id = v_order.id;

  INSERT INTO public.marketplace_messages (listing_id, sender_id, receiver_id, kind, body)
  VALUES (v_listing.id, v_uid, CASE WHEN v_uid = v_order.buyer_id THEN v_order.seller_id ELSE v_order.buyer_id END, 'system', '訂單已取消');

  RETURN jsonb_build_object('success', true);
END;
$$;

ALTER FUNCTION public.cancel_marketplace_order(BIGINT) SET row_security = off;

NOTIFY pgrst, 'reload schema';

COMMIT;

