CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Core public catalog tables
CREATE TABLE IF NOT EXISTS public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) NOT NULL UNIQUE,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.categories (name, sort_order)
VALUES
  ('一番賞', 1),
  ('線上抽', 2),
  ('盲盒', 3),
  ('3C', 4),
  ('福袋', 5)
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code VARCHAR(50),
  name VARCHAR(255) NOT NULL DEFAULT '未命名商品',
  category VARCHAR(50) DEFAULT '未分類',
  category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  remaining INTEGER NOT NULL DEFAULT 0,
  remaining_count INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  sales INTEGER DEFAULT 0,
  is_hot BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  txid_hash TEXT,
  seed TEXT,
  image_url TEXT,
  release_year VARCHAR(10),
  release_month VARCHAR(10),
  distributor VARCHAR(100),
  rarity INTEGER,
  total_count INTEGER DEFAULT 0,
  major_prizes TEXT[] DEFAULT ARRAY[]::TEXT[],
  description TEXT,
  type TEXT DEFAULT 'ichiban',
  is_active BOOLEAN DEFAULT TRUE,
  metadata JSONB DEFAULT '{}'::jsonb,
  profit_rate NUMERIC(5, 2) DEFAULT 1.0,
  view_count BIGINT DEFAULT 0
);

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_code VARCHAR(50);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS remaining INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS remaining_count INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sales INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_hot BOOLEAN DEFAULT FALSE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS txid_hash TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS seed TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS release_year VARCHAR(10);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS release_month VARCHAR(10);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS distributor VARCHAR(100);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS rarity INTEGER;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS total_count INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS major_prizes TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'ichiban';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS profit_rate NUMERIC(5, 2) DEFAULT 1.0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS view_count BIGINT DEFAULT 0;

UPDATE public.products
SET
  name = COALESCE(NULLIF(name, ''), '未命名商品'),
  category = COALESCE(NULLIF(category, ''), '未分類'),
  status = COALESCE(NULLIF(status, ''), 'pending'),
  type = COALESCE(NULLIF(type, ''), 'ichiban'),
  remaining = COALESCE(remaining, remaining_count, 0),
  remaining_count = COALESCE(remaining_count, remaining, 0),
  total_count = COALESCE(total_count, remaining_count, remaining, 0),
  price = COALESCE(price, 0),
  is_hot = COALESCE(is_hot, FALSE),
  is_active = COALESCE(is_active, TRUE),
  view_count = COALESCE(view_count, 0)
WHERE TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_products_product_code_unique
  ON public.products(product_code)
  WHERE product_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_is_hot ON public.products(is_hot);

CREATE TABLE IF NOT EXISTS public.product_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  level VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  image_url TEXT,
  total INTEGER NOT NULL DEFAULT 0,
  remaining INTEGER NOT NULL DEFAULT 0,
  probability NUMERIC(10, 6) NOT NULL DEFAULT 0,
  recycle_value INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_last_one BOOLEAN DEFAULT FALSE
);

ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS level VARCHAR(50);
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS total INTEGER DEFAULT 0;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS remaining INTEGER DEFAULT 0;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS probability NUMERIC(10, 6) DEFAULT 0;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS recycle_value INTEGER DEFAULT 0;
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.product_prizes ADD COLUMN IF NOT EXISTS is_last_one BOOLEAN DEFAULT FALSE;

UPDATE public.product_prizes
SET
  level = COALESCE(NULLIF(level, ''), '未分級'),
  name = COALESCE(NULLIF(name, ''), '未命名獎項'),
  total = COALESCE(total, remaining, 0),
  remaining = COALESCE(remaining, total, 0),
  probability = COALESCE(probability, 0),
  recycle_value = COALESCE(recycle_value, 0),
  is_last_one = COALESCE(is_last_one, FALSE)
WHERE TRUE;

CREATE INDEX IF NOT EXISTS idx_product_prizes_product_id ON public.product_prizes(product_id);

CREATE TABLE IF NOT EXISTS public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  image_url TEXT NOT NULL DEFAULT '',
  link_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS link_url TEXT;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.banners ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.banners
SET
  image_url = COALESCE(image_url, ''),
  sort_order = COALESCE(sort_order, 0),
  is_active = COALESCE(is_active, TRUE)
WHERE TRUE;

INSERT INTO storage.buckets (id, name, public)
VALUES ('banners', 'banners', true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.news (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  view_count INTEGER DEFAULT 0
);

ALTER TABLE public.news ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;

UPDATE public.news
SET
  is_active = COALESCE(is_active, TRUE),
  view_count = COALESCE(view_count, 0)
WHERE TRUE;

-- Transaction tables
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  recipient_name VARCHAR(100),
  recipient_phone VARCHAR(50),
  address TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'submitted',
  tracking_number VARCHAR(100),
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  shipped_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  total_amount NUMERIC(10, 2) DEFAULT 0,
  logistics_type VARCHAR(20) DEFAULT 'HOME',
  logistics_subtype VARCHAR(20),
  store_id VARCHAR(50),
  store_name VARCHAR(100),
  logistics_status TEXT DEFAULT 'pending',
  payment_method TEXT,
  coupon_id BIGINT,
  coupon_discount NUMERIC(10, 2) DEFAULT 0
);

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS order_number VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(100);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS recipient_phone VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'submitted';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_amount NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS logistics_type VARCHAR(20) DEFAULT 'HOME';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS logistics_subtype VARCHAR(20);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_id VARCHAR(50);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_name VARCHAR(100);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS logistics_status TEXT DEFAULT 'pending';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_id BIGINT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_discount NUMERIC(10, 2) DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_name VARCHAR(255),
  prize_name VARCHAR(255),
  prize_level VARCHAR(50),
  image_url TEXT,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL,
  quantity INTEGER DEFAULT 1,
  price NUMERIC(10, 2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS product_name VARCHAR(255);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS prize_name VARCHAR(255);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS prize_level VARCHAR(50);
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);

CREATE TABLE IF NOT EXISTS public.draw_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL,
  prize_level VARCHAR(50),
  prize_name VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  txid_nonce BIGINT,
  ticket_number INTEGER,
  txid_hash TEXT,
  txid_seed TEXT,
  status VARCHAR(50) DEFAULT 'success',
  profit_rate NUMERIC(5, 2) DEFAULT 1.0,
  random_value NUMERIC,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL
);

ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS prize_level VARCHAR(50);
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS prize_name VARCHAR(255);
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS txid_nonce BIGINT;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS ticket_number INTEGER;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS txid_hash TEXT;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS txid_seed TEXT;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'success';
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS profit_rate NUMERIC(5, 2) DEFAULT 1.0;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS random_value NUMERIC;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_draw_records_user_id ON public.draw_records(user_id);
CREATE INDEX IF NOT EXISTS idx_draw_records_product_id ON public.draw_records(product_id);

CREATE TABLE IF NOT EXISTS public.recharge_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(100),
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  amount NUMERIC(10, 2) DEFAULT 0,
  bonus NUMERIC(10, 2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS order_number VARCHAR(100);
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS amount NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS bonus NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_recharge_records_user_id ON public.recharge_records(user_id);

-- Support / analytics tables
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  link TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS link TEXT;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS meta JSONB;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.visit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT NOT NULL,
  user_agent TEXT,
  ip_address TEXT,
  referrer TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  result_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.small_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.action_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  detail JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

NOTIFY pgrst, 'reload schema';
