-- 185_safe_primary_bootstrap.sql
-- Safe idempotent bootstrap for ALL core (primary) tables.
-- Uses CREATE TABLE IF NOT EXISTS + ALTER TABLE ADD COLUMN IF NOT EXISTS.
-- Does NOT drop or truncate any table. Safe to run on existing data.
--
-- IMPORTANT: Run this BEFORE 186_safe_secondary_bootstrap.sql.
-- 186 adds dependent tables (marketplace, exchange, tags) that reference these.

BEGIN;

-- =========================================================
-- 0. Extensions
-- =========================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================================================
-- 1. Categories
-- =========================================================

CREATE TABLE IF NOT EXISTS public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL UNIQUE,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.categories;
CREATE POLICY "Allow public read access" ON public.categories FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Allow admin full access" ON public.categories;
CREATE POLICY "Allow admin full access" ON public.categories FOR ALL USING (TRUE) WITH CHECK (TRUE);

INSERT INTO public.categories (name, sort_order) VALUES
  ('一番賞', 1), ('線上抽', 2), ('盲盒', 3), ('3C', 4), ('福袋', 5)
ON CONFLICT (name) DO NOTHING;

-- =========================================================
-- 2. Products
-- =========================================================

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL DEFAULT 0,
  image_url TEXT,
  type TEXT NOT NULL DEFAULT 'ichiban',
  status TEXT NOT NULL DEFAULT 'active',
  is_hot BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  total_count INTEGER NOT NULL DEFAULT 0,
  remaining INTEGER NOT NULL DEFAULT 0,
  category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
  category TEXT DEFAULT '未分類',
  product_code TEXT,
  major_prizes TEXT[] DEFAULT ARRAY[]::TEXT[],
  metadata JSONB DEFAULT '{}'::jsonb,
  seed TEXT,
  txid_hash TEXT,
  profit_rate NUMERIC(10, 2) DEFAULT 1.0,
  release_date TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  product_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safe add of type check constraint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.products'::regclass AND conname = 'products_type_check'
  ) THEN
    ALTER TABLE public.products ADD CONSTRAINT products_type_check
      CHECK (type IN ('ichiban', 'gacha', 'blindbox', 'card', 'custom', 'ticket'));
  END IF;
END $$;

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Products are viewable by everyone" ON public.products;
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Products are manageable" ON public.products;
CREATE POLICY "Products are manageable" ON public.products FOR ALL USING (TRUE) WITH CHECK (TRUE);

CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_is_hot ON public.products(is_hot);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON public.products(created_at DESC);

-- Products storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', TRUE)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access Products" ON storage.objects;
CREATE POLICY "Public Access Products" ON storage.objects FOR ALL
  USING (bucket_id = 'products') WITH CHECK (bucket_id = 'products');

-- =========================================================
-- 3. Product Prizes
-- =========================================================

CREATE TABLE IF NOT EXISTS public.product_prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  level VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  image_url TEXT,
  total INTEGER NOT NULL DEFAULT 0,
  remaining INTEGER NOT NULL DEFAULT 0,
  probability NUMERIC(5, 2) NOT NULL DEFAULT 0,
  recycle_value INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.product_prizes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Product prizes viewable by everyone" ON public.product_prizes;
CREATE POLICY "Product prizes viewable by everyone" ON public.product_prizes FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Product prizes manageable" ON public.product_prizes;
CREATE POLICY "Product prizes manageable" ON public.product_prizes FOR ALL USING (TRUE) WITH CHECK (TRUE);

CREATE INDEX IF NOT EXISTS idx_product_prizes_product_id ON public.product_prizes(product_id);

-- =========================================================
-- 4. Product Ticket Plans
-- =========================================================

CREATE TABLE IF NOT EXISTS public.product_ticket_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  ticket_count INTEGER NOT NULL,
  price INTEGER NOT NULL,
  currency TEXT DEFAULT 'TWD',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.product_ticket_plan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Ticket plans viewable by everyone" ON public.product_ticket_plan;
CREATE POLICY "Ticket plans viewable by everyone" ON public.product_ticket_plan FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Ticket plans manageable" ON public.product_ticket_plan;
CREATE POLICY "Ticket plans manageable" ON public.product_ticket_plan FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- =========================================================
-- 5. Orders
-- =========================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(50) UNIQUE,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  recipient_name VARCHAR(100),
  recipient_phone VARCHAR(50),
  address TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'submitted',
  tracking_number VARCHAR(100),
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  shipped_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.orders'::regclass AND conname = 'orders_status_check'
  ) THEN
    ALTER TABLE public.orders ADD CONSTRAINT orders_status_check
      CHECK (status IN ('submitted', 'processing', 'picked_up', 'shipping', 'delivered', 'cancelled'));
  END IF;
END $$;

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own orders" ON public.orders;
CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own orders" ON public.orders;
CREATE POLICY "Users can insert their own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_submitted_at ON public.orders(submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);

-- =========================================================
-- 6. Draw Records
-- =========================================================

CREATE TABLE IF NOT EXISTS public.draw_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL,
  prize_name TEXT,
  prize_level TEXT,
  prize_image_url TEXT,
  ticket_number INTEGER,
  txid_nonce BIGINT,
  txid_hash TEXT,
  status TEXT DEFAULT 'success',
  profit_rate NUMERIC(5, 2) DEFAULT 1.0,
  random_value NUMERIC,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  is_tradable BOOLEAN DEFAULT TRUE,
  is_last_one BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safely replace status check constraint to include all valid states
DO $$
DECLARE r RECORD;
BEGIN
  SELECT conname INTO r FROM pg_constraint
  WHERE conrelid = 'public.draw_records'::regclass AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%status%';
  IF FOUND THEN
    EXECUTE 'ALTER TABLE public.draw_records DROP CONSTRAINT ' || r.conname;
  END IF;
END $$;

ALTER TABLE public.draw_records ADD CONSTRAINT draw_records_status_check
  CHECK (status IN ('success', 'in_warehouse', 'pending_delivery', 'shipped', 'exchanged', 'dismantled', 'listing', 'cancelled'));

ALTER TABLE public.draw_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own draw records" ON public.draw_records;
CREATE POLICY "Users can view their own draw records" ON public.draw_records FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert draw records" ON public.draw_records;
CREATE POLICY "Users can insert draw records" ON public.draw_records FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Users can update their own draw records" ON public.draw_records;
CREATE POLICY "Users can update their own draw records" ON public.draw_records FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_draw_records_user_id ON public.draw_records(user_id);
CREATE INDEX IF NOT EXISTS idx_draw_records_product_id ON public.draw_records(product_id);
CREATE INDEX IF NOT EXISTS idx_draw_records_created_at ON public.draw_records(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_draw_records_status ON public.draw_records(status);

-- =========================================================
-- 7. Order Items
-- =========================================================

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_prize_id BIGINT REFERENCES public.product_prizes(id) ON DELETE SET NULL,
  price INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Order items viewable by order owner" ON public.order_items;
CREATE POLICY "Order items viewable by order owner" ON public.order_items FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = auth.uid()));
DROP POLICY IF EXISTS "Order items insertable" ON public.order_items;
CREATE POLICY "Order items insertable" ON public.order_items FOR INSERT WITH CHECK (TRUE);

-- =========================================================
-- 8. Recharge Records
-- =========================================================

CREATE TABLE IF NOT EXISTS public.recharge_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number VARCHAR(100),
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  bonus NUMERIC(10, 2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'pending',
  payment_method VARCHAR(50),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.recharge_records'::regclass AND conname = 'recharge_records_status_check'
  ) THEN
    ALTER TABLE public.recharge_records ADD CONSTRAINT recharge_records_status_check
      CHECK (status IN ('success', 'pending', 'failed'));
  END IF;
END $$;

ALTER TABLE public.recharge_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own recharge records" ON public.recharge_records;
CREATE POLICY "Users can view their own recharge records" ON public.recharge_records FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own recharge records" ON public.recharge_records;
CREATE POLICY "Users can insert their own recharge records" ON public.recharge_records FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_recharge_records_user_id ON public.recharge_records(user_id);
CREATE INDEX IF NOT EXISTS idx_recharge_records_created_at ON public.recharge_records(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recharge_records_status ON public.recharge_records(status);

-- =========================================================
-- 9. Banners
-- =========================================================

CREATE TABLE IF NOT EXISTS public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  image_url TEXT NOT NULL,
  link_url TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Banners viewable by everyone" ON public.banners;
CREATE POLICY "Banners viewable by everyone" ON public.banners FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Banners manageable" ON public.banners;
CREATE POLICY "Banners manageable" ON public.banners FOR ALL USING (TRUE) WITH CHECK (TRUE);

INSERT INTO storage.buckets (id, name, public)
VALUES ('banners', 'banners', TRUE)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access Banners" ON storage.objects;
CREATE POLICY "Public Access Banners" ON storage.objects FOR ALL
  USING (bucket_id = 'banners') WITH CHECK (bucket_id = 'banners');

-- =========================================================
-- 10. News
-- =========================================================

CREATE TABLE IF NOT EXISTS public.news (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  title TEXT NOT NULL,
  content TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  view_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.news;
CREATE POLICY "Allow public read access" ON public.news FOR SELECT USING (TRUE);
DROP POLICY IF EXISTS "Allow public insert access" ON public.news;
CREATE POLICY "Allow public insert access" ON public.news FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Allow public update access" ON public.news;
CREATE POLICY "Allow public update access" ON public.news FOR UPDATE USING (TRUE);
DROP POLICY IF EXISTS "Allow public delete access" ON public.news;
CREATE POLICY "Allow public delete access" ON public.news FOR DELETE USING (TRUE);

-- =========================================================
-- 11. Notifications
-- =========================================================

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  link TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own notifications" ON public.notifications;
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own notifications" ON public.notifications;
CREATE POLICY "Users can insert own notifications" ON public.notifications FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);

-- =========================================================
-- 12. Small Items
-- =========================================================

CREATE TABLE IF NOT EXISTS public.small_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  image_url TEXT,
  category TEXT,
  level TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.small_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.small_items;
CREATE POLICY "Allow read access to authenticated users" ON public.small_items
  FOR SELECT TO authenticated USING (TRUE);
DROP POLICY IF EXISTS "Allow write access to authenticated users" ON public.small_items;
CREATE POLICY "Allow write access to authenticated users" ON public.small_items
  FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- =========================================================
-- 13. Action Logs
-- =========================================================

CREATE TABLE IF NOT EXISTS public.action_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT REFERENCES public.admins(id) ON DELETE SET NULL,
  username VARCHAR(50) NOT NULL,
  role VARCHAR(50),
  action VARCHAR(50) NOT NULL,
  target VARCHAR(100),
  details TEXT,
  ip VARCHAR(50),
  status VARCHAR(20) DEFAULT 'success',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.action_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can insert logs" ON public.action_logs;
CREATE POLICY "Admins can insert logs" ON public.action_logs FOR INSERT TO public WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Admins can view logs" ON public.action_logs;
CREATE POLICY "Admins can view logs" ON public.action_logs FOR SELECT TO public USING (TRUE);

CREATE INDEX IF NOT EXISTS idx_action_logs_created_at ON public.action_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_logs_admin_id ON public.action_logs(admin_id);

-- =========================================================
-- 14. Analytics (visit_logs, search_logs)
-- =========================================================

CREATE TABLE IF NOT EXISTS public.visit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.search_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb
);

ALTER TABLE public.visit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "visit_logs insert" ON public.visit_logs;
CREATE POLICY "visit_logs insert" ON public.visit_logs FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "visit_logs read" ON public.visit_logs;
CREATE POLICY "visit_logs read" ON public.visit_logs FOR SELECT USING (TRUE);

ALTER TABLE public.search_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "search_logs insert" ON public.search_logs;
CREATE POLICY "search_logs insert" ON public.search_logs FOR INSERT WITH CHECK (TRUE);
DROP POLICY IF EXISTS "search_logs read" ON public.search_logs;
CREATE POLICY "search_logs read" ON public.search_logs FOR SELECT USING (TRUE);

CREATE INDEX IF NOT EXISTS idx_visit_logs_created_at ON public.visit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON public.search_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_search_logs_keyword ON public.search_logs(keyword);

-- =========================================================
-- 15. Daily Check-ins
-- =========================================================

CREATE TABLE IF NOT EXISTS public.daily_check_ins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  check_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, check_in_date)
);

ALTER TABLE public.daily_check_ins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own check-ins" ON public.daily_check_ins;
CREATE POLICY "Users can view own check-ins" ON public.daily_check_ins FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own check-ins" ON public.daily_check_ins;
CREATE POLICY "Users can insert own check-ins" ON public.daily_check_ins FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =========================================================
-- 16. Backfill missing columns on EXISTING tables
--     (CREATE TABLE IF NOT EXISTS above is skipped if table exists)
-- =========================================================

-- draw_records: marketplace & tradability flags
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS is_tradable BOOLEAN DEFAULT TRUE;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS is_last_one BOOLEAN DEFAULT FALSE;
ALTER TABLE public.draw_records ADD COLUMN IF NOT EXISTS prize_image_url TEXT;

-- recharge_records: payment tracking
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.recharge_records ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);

-- products: audit timestamp + product_type discriminator
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_type TEXT;

-- =========================================================
-- 17. Payment functions (topup)
-- =========================================================

CREATE OR REPLACE FUNCTION public.create_topup_order(
  p_amount DECIMAL,
  p_bonus DECIMAL,
  p_payment_method VARCHAR DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
  v_user_id UUID;
  v_order_number VARCHAR(50);
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  v_order_number := 'TP' || to_char(now(), 'YYMMDD') || lpad(floor(random() * 10000)::text, 4, '0');

  INSERT INTO public.recharge_records (order_number, user_id, amount, bonus, status, payment_method)
  VALUES (v_order_number, v_user_id, p_amount, p_bonus, 'pending', p_payment_method);

  RETURN json_build_object('success', true, 'order_number', v_order_number);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.create_topup_order(DECIMAL, DECIMAL, VARCHAR) TO authenticated;

CREATE OR REPLACE FUNCTION public.confirm_topup_order(p_order_number VARCHAR) RETURNS JSON AS $$
DECLARE
  v_record RECORD;
  v_total_tokens INTEGER;
  v_new_balance INTEGER;
BEGIN
  SELECT * INTO v_record FROM public.recharge_records
  WHERE order_number = p_order_number AND status = 'pending' FOR UPDATE;

  IF NOT FOUND THEN
    IF EXISTS (SELECT 1 FROM public.recharge_records WHERE order_number = p_order_number AND status = 'success') THEN
      RETURN json_build_object('success', true, 'message', 'Already confirmed');
    END IF;
    RAISE EXCEPTION 'Order not found or not pending';
  END IF;

  v_total_tokens := (v_record.amount + v_record.bonus)::INTEGER;

  UPDATE public.recharge_records SET status = 'success', updated_at = NOW() WHERE id = v_record.id;
  UPDATE public.users SET tokens = tokens + v_total_tokens WHERE id = v_record.user_id RETURNING tokens INTO v_new_balance;

  INSERT INTO public.notifications (user_id, type, title, body, link, meta)
  VALUES (
    v_record.user_id, 'topup', '儲值成功通知',
    format('您成功儲值 %s 元，獲得 %s 代幣（含贈送 %s）', v_record.amount, v_total_tokens, v_record.bonus),
    '/profile?tab=topup-history',
    jsonb_build_object(
      'order_number', p_order_number,
      'amount', v_record.amount,
      'bonus', v_record.bonus,
      'added_tokens', v_total_tokens,
      'new_balance', v_new_balance
    )
  );

  RETURN json_build_object('success', true, 'order_number', p_order_number, 'new_balance', v_new_balance);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =========================================================
-- Done
-- =========================================================

NOTIFY pgrst, 'reload schema';

COMMIT;
