-- 187_suppliers.sql
-- 新增廠商（suppliers）表，並在 products 加入 supplier_id FK。
-- 使用 CREATE TABLE IF NOT EXISTS，不 DROP 任何現有資料，可安全重複執行。

BEGIN;

-- =========================================================
-- 1. suppliers 表
-- =========================================================

CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_name TEXT,
  contact_phone TEXT,
  contact_email TEXT,
  address TEXT,
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Suppliers admin access" ON public.suppliers;
CREATE POLICY "Suppliers admin access" ON public.suppliers FOR ALL USING (TRUE) WITH CHECK (TRUE);

CREATE INDEX IF NOT EXISTS idx_suppliers_is_active ON public.suppliers(is_active);

-- =========================================================
-- 2. 在 products 加入 supplier_id（可選 FK，保留歷史商品不受影響）
-- =========================================================

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON public.products(supplier_id);

-- =========================================================
-- 3. 預設廠商（靈感文創合作）
-- =========================================================

INSERT INTO public.suppliers (name, contact_name, notes)
VALUES ('靈感文創', NULL, '主要合作廠商')
ON CONFLICT DO NOTHING;

COMMIT;
