-- 193_dev_logs.sql
-- 開發紀錄：版本 changelog + 問題追蹤

CREATE TABLE IF NOT EXISTS public.dev_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version     VARCHAR(20),        -- e.g. "v1.2.0"，問題類型可為 NULL
  title       TEXT NOT NULL,
  description TEXT,
  type        VARCHAR(20) NOT NULL CHECK (type IN ('feature','fix','improvement','issue')),
  status      VARCHAR(20) NOT NULL DEFAULT 'open'
                CHECK (status IN ('released','planned','open','in_progress','resolved')),
  priority    VARCHAR(10) CHECK (priority IN ('high','medium','low')),
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.dev_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dev_logs admin access" ON public.dev_logs;
CREATE POLICY "dev_logs admin access" ON public.dev_logs FOR ALL USING (TRUE) WITH CHECK (TRUE);

CREATE INDEX IF NOT EXISTS idx_dev_logs_type   ON public.dev_logs(type);
CREATE INDEX IF NOT EXISTS idx_dev_logs_status ON public.dev_logs(status);

-- 初始種子資料（近期已發布的版本）
INSERT INTO public.dev_logs (version, title, description, type, status, created_at) VALUES
  ('v1.0.0', '平台上線', '前台 + 後台基礎功能：會員登入、轉蛋抽獎、儲值（藍新金流）、倉庫', 'feature', 'released', NOW() - INTERVAL '30 days'),
  ('v1.1.0', '廠商結算報表', '廠商結算頁面：月結期別、費率設定、匯出對帳單 CSV', 'feature', 'released', NOW() - INTERVAL '14 days'),
  ('v1.1.1', '藍新手續費依付款方式計算', '於 callback 時依 PaymentType 計算實際手續費並存入 DB', 'improvement', 'released', NOW() - INTERVAL '10 days'),
  ('v1.1.2', '廠商結算改為消費基底', '結算基底從儲值金額改為廠商商品消費 G，支援多廠商佔比分攤', 'fix', 'released', NOW() - INTERVAL '2 days'),
  ('v1.2.0', '營運總覽新增轉換漏斗', '轉換漏斗（新用戶→首購→回購）、付費行為分析、首購時間分佈', 'feature', 'released', NOW() - INTERVAL '1 day'),
  ('v1.2.0', '簽到 / 測試儲值 / 分解功能修復', '補建遺失的三個 DB 函數（daily_check_in、process_test_topup、dismantle_prizes）', 'fix', 'released', NOW() - INTERVAL '1 day')
ON CONFLICT DO NOTHING;
