BEGIN;

CREATE TABLE IF NOT EXISTS public.product_follows (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, product_id)
);

ALTER TABLE public.product_follows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own follows" ON public.product_follows;
CREATE POLICY "Users can manage their own follows"
  ON public.product_follows
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_product_follows_user    ON public.product_follows(user_id);
CREATE INDEX IF NOT EXISTS idx_product_follows_product ON public.product_follows(product_id);

COMMIT;
