-- W5-4: 競品情報 + 每週 AI 分析報告

CREATE TABLE IF NOT EXISTS competitor_posts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor   TEXT NOT NULL,          -- 競品名稱，例如「扭蛋王」
  platform     TEXT,                   -- 來源平台，例如「IG」「Threads」「FB」
  content      TEXT NOT NULL,          -- 貼文內容（手動貼入）
  url          TEXT,                   -- 原始連結（選填）
  added_by     TEXT NOT NULL DEFAULT 'admin',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS competitor_reports (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_start TIMESTAMPTZ NOT NULL,
  period_end   TIMESTAMPTZ NOT NULL,
  post_count   INTEGER NOT NULL DEFAULT 0,
  analysis     TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_competitor_posts_created ON competitor_posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_competitor_reports_created ON competitor_reports (created_at DESC);
