-- 市場情報官 v2：結構化競品追蹤 + 關鍵字掃描 + 深度分析存底

-- 競品追蹤清單
CREATE TABLE IF NOT EXISTS competitor_watchlist (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  url           TEXT NOT NULL,
  social_urls   JSONB NOT NULL DEFAULT '[]',
  status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'candidate', 'removed')),
  discovered_by TEXT NOT NULL DEFAULT 'manual',
  notes         TEXT,
  added_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 關鍵字掃描記錄
CREATE TABLE IF NOT EXISTS market_keyword_scan_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  keywords     TEXT[] NOT NULL,
  findings     TEXT,
  new_platforms TEXT[] NOT NULL DEFAULT '{}',
  result_count INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 完整分析存底（四層分析 + 最終報告）
CREATE TABLE IF NOT EXISTS market_intel_analysis (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date      DATE NOT NULL DEFAULT CURRENT_DATE,
  run_type      TEXT NOT NULL DEFAULT 'weekly'
                  CHECK (run_type IN ('weekly', 'discovery', 'anomaly', 'manual')),
  competitors_scraped INTEGER NOT NULL DEFAULT 0,
  facts_layer   TEXT,
  insight_layer TEXT,
  compare_layer TEXT,
  suggest_layer TEXT,
  report        TEXT,
  anomalies     JSONB NOT NULL DEFAULT '[]',
  raw_data      JSONB NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_competitor_watchlist_status  ON competitor_watchlist (status);
CREATE INDEX IF NOT EXISTS idx_market_kw_scan_date          ON market_keyword_scan_logs (scan_date DESC);
CREATE INDEX IF NOT EXISTS idx_market_intel_analysis_date   ON market_intel_analysis (run_date DESC);
