-- 409: 機台中獎彈幕的機器人資料（純展示，與交易資料完全隔離）
--
-- 目的：平台初期真人中獎稀少，彈幕會幾乎不動，比不做還尷尬。
--
-- 為何不寫進 slot_spin_logs：
--   該表是機台報表（營收／派彩／RTP）與消費明細的資料來源，
--   灌入機器人資料會直接污染財務數字，也會需要動 product_prizes 庫存。
--   故改為獨立的展示專用表 —— 任何報表 query 都不會碰到這張表，
--   庫存、draw_records、token_ledger 一律不受影響。
--
-- 與排行榜、首頁跑馬燈同樣的原則：機器人只影響「看起來熱鬧」，不影響帳。
-- 卡牌名稱取自機台獎池的真實品項，不是憑空捏造的卡名。

BEGIN;

CREATE TABLE IF NOT EXISTS public.slot_danmaku_bots (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  prize_name  TEXT NOT NULL,
  prize_value BIGINT NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.slot_danmaku_bots IS
  '機台彈幕的機器人展示資料。純顯示用，不進報表、不扣庫存、不影響任何財務數字。';

ALTER TABLE public.slot_danmaku_bots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.slot_danmaku_bots FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_slot_danmaku_bots_created_at
  ON public.slot_danmaku_bots(created_at DESC);

-- 重新產生：每個機器人 2~4 筆，卡牌取自機台 RUSH 獎池的真實品項
DELETE FROM public.slot_danmaku_bots;

INSERT INTO public.slot_danmaku_bots (user_id, prize_name, prize_value, created_at)
SELECT
  b.id,
  p.name,
  p.recycle_value,
  now() - (random() * interval '7 days')
FROM (SELECT id FROM public.users WHERE is_bot = TRUE) b
CROSS JOIN LATERAL (
  SELECT pp.name, COALESCE(pp.recycle_value, 0) AS recycle_value
  FROM public.slot_pool_items spi
  JOIN public.product_prizes pp ON pp.id = spi.product_prize_id
  WHERE spi.rush_only = TRUE AND pp.name IS NOT NULL
  ORDER BY random()
  LIMIT (2 + floor(random() * 3)::int)
) p;

COMMIT;
