-- 552_sell_marketplace_governance.sql
--
-- 玩家商城（sell_*）治理層：類別白名單、上架審核、單一收款方式、檢舉與停權。
--
-- ⚠️ 這裡動的是「玩家商城」= sell_listings / sell_orders / sell_seller_profiles。
--    站上另外還有兩套長得很像、但完全不同的東西，不要改到：
--      · marketplace_*  → 交易所（倉庫裡的大賞轉手，貨不離開平台倉庫）
--      · exchange_*     → 卡牌交換（以物易物，沒有金流）
--
-- ── 金流定位（決定了這支 migration 為什麼長這樣）──
-- 玩家商城**平台完全不碰錢**：買家直接把錢匯給賣家（銀行轉帳或 LINE Pay），
-- 平台只提供媒合、交易紀錄與物流。因此：
--   · 沒有代收、沒有平台餘額、沒有提領 → 這些表一律不建
--   · 也收不到成交抽成 → 平台明講不收服務費，商城定位是引流與留客
--   · 相對地，平台要能「有話可說」：實名（手機驗證）、檢舉、停權、完整紀錄
-- 官方商城（GGB 自售）走綠界，是另一條軌道，不在這支 migration 內。

BEGIN;

-- ============================================================
-- A. sell_listings：類別 + 上架審核
-- ============================================================

ALTER TABLE public.sell_listings
  ADD COLUMN IF NOT EXISTS category    text,
  ADD COLUMN IF NOT EXISTS review_note text,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by text;

COMMENT ON COLUMN public.sell_listings.category    IS '類別，必須在 platform_settings.sell_category_whitelist 內';
COMMENT ON COLUMN public.sell_listings.review_note IS '退回原因，會顯示給賣家看';

-- 狀態機：
--   pending  待審（玩家上架後的預設）
--   active   上架中
--   rejected 審核退回
--   sold     全部品項售罄（既有值，create_sell_order 會設）
--   removed  賣家自行下架 / 後台強制下架
ALTER TABLE public.sell_listings ALTER COLUMN status SET DEFAULT 'pending';

ALTER TABLE public.sell_listings DROP CONSTRAINT IF EXISTS sell_listings_status_check;
ALTER TABLE public.sell_listings
  ADD CONSTRAINT sell_listings_status_check
  CHECK (status IN ('pending','active','rejected','sold','removed'));

CREATE INDEX IF NOT EXISTS idx_sell_listings_status_created
  ON public.sell_listings (status, created_at DESC);

-- ============================================================
-- B. sell_seller_profiles：單一收款方式 + 停權
-- ============================================================
--
-- 老闆指示：「不用多填，因為賣家就想要特定一種收款方式，那是他的自由」
-- → 賣家只選一種，買家照著付。不做多選、不做買家挑。

ALTER TABLE public.sell_seller_profiles
  ADD COLUMN IF NOT EXISTS payout_method   text NOT NULL DEFAULT 'bank',
  ADD COLUMN IF NOT EXISTS linepay_id      text,
  ADD COLUMN IF NOT EXISTS suspended_at    timestamptz,
  ADD COLUMN IF NOT EXISTS suspend_reason  text,
  ADD COLUMN IF NOT EXISTS suspended_by    text;

ALTER TABLE public.sell_seller_profiles DROP CONSTRAINT IF EXISTS sell_seller_profiles_payout_method_check;
ALTER TABLE public.sell_seller_profiles
  ADD CONSTRAINT sell_seller_profiles_payout_method_check
  CHECK (payout_method IN ('bank','linepay'));

COMMENT ON COLUMN public.sell_seller_profiles.payout_method IS 'bank=銀行轉帳｜linepay=LINE Pay，賣家二選一';
COMMENT ON COLUMN public.sell_seller_profiles.linepay_id    IS 'LINE Pay 收款用的手機號或 ID';
COMMENT ON COLUMN public.sell_seller_profiles.suspended_at  IS '賣家停權時間；非 NULL 即不能上架也不能被下單';

-- 面交移除：零紀錄、糾紛完全無解，老闆確認拿掉。
-- （表內 0 筆資料，直接刪欄位不會掉東西）
ALTER TABLE public.sell_seller_profiles DROP COLUMN IF EXISTS private_trade_note;

-- ============================================================
-- C. sell_reports：檢舉
-- ============================================================
--
-- 平台不碰錢，出事時唯一能拿出來的就是紀錄。
-- 這張表是「誰檢舉了誰、為什麼、後台怎麼處理」的完整軌跡。

CREATE TABLE IF NOT EXISTS public.sell_reports (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id  uuid   NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  target_type  text   NOT NULL CHECK (target_type IN ('listing','order','seller')),
  listing_id   bigint REFERENCES public.sell_listings(id) ON DELETE SET NULL,
  order_id     bigint REFERENCES public.sell_orders(id)   ON DELETE SET NULL,
  seller_id    uuid   REFERENCES public.users(id)         ON DELETE SET NULL,
  reason       text   NOT NULL,
  detail       text,
  images       text[] NOT NULL DEFAULT '{}',
  status       text   NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved','dismissed')),
  admin_note   text,
  handled_at   timestamptz,
  handled_by   text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sell_reports_status  ON public.sell_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sell_reports_seller  ON public.sell_reports (seller_id);

ALTER TABLE public.sell_reports ENABLE ROW LEVEL SECURITY;

-- ⚠️ 有 RLS 就一定要有 policy，否則前台讀不到會**靜默回空陣列**（不會報錯）
DROP POLICY IF EXISTS "Sell reports - own view"   ON public.sell_reports;
DROP POLICY IF EXISTS "Sell reports - create"     ON public.sell_reports;

CREATE POLICY "Sell reports - own view" ON public.sell_reports
  FOR SELECT USING (reporter_id = auth.uid());

CREATE POLICY "Sell reports - create" ON public.sell_reports
  FOR INSERT WITH CHECK (reporter_id = auth.uid());

-- 後台走 service_role，不受 RLS 限制，所以不需要 admin policy。

-- ============================================================
-- D. 販售設定（platform_settings，key/value 都是 text）
-- ============================================================

INSERT INTO public.platform_settings (key, value) VALUES
  ('sell_category_whitelist',
   '["一番賞","盒玩","轉蛋","卡牌","公仔模型","周邊商品"]'),
  ('sell_require_phone_verified', 'true'),
  ('sell_max_active_listings',    '20'),
  ('sell_pay_deadline_hours',     '48'),
  ('sell_ship_deadline_days',     '7'),
  ('sell_receive_deadline_days',  '7'),
  ('sell_disclaimer',
   '本交易的付款由買賣雙方自行完成，GGB 不經手款項、不收取成交手續費，亦無法介入金流糾紛。請務必確認對方身分與商品狀況後再付款。')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- E. 權限判斷：誰可以繞過賣家限制
-- ============================================================
--
-- 站內的 SECURITY DEFINER 函式（create_sell_order / cancel_sell_order …）都有
-- `SET row_security TO 'off'`，後台則是用 service_role key。兩者都算「內部」，
-- 不該被下面的賣家守則擋住。

CREATE OR REPLACE FUNCTION public.sell_is_privileged()
RETURNS boolean
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  IF current_setting('row_security', true) = 'off' THEN
    RETURN true;
  END IF;
  IF COALESCE(current_setting('request.jwt.claims', true)::jsonb ->> 'role', '') = 'service_role' THEN
    RETURN true;
  END IF;
  RETURN false;
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;

-- ============================================================
-- F. 上架守則（trigger）
-- ============================================================
--
-- 為什麼一定要 trigger、RLS 不夠：
-- `Sell listings - seller manage` 是 `FOR ALL USING (seller_id = auth.uid())`，
-- 賣家可以直接 `UPDATE sell_listings SET status='active'` 自我核准 —— 審核等於沒有。
-- RLS 的 WITH CHECK 看不到 OLD，判斷不了「從哪個狀態改到哪個狀態」，所以用 trigger。

CREATE OR REPLACE FUNCTION public.sell_guard_listing()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_whitelist   jsonb;
  v_need_phone  boolean;
  v_max_active  int;
  v_active_cnt  int;
BEGIN
  IF public.sell_is_privileged() THEN
    RETURN NEW;
  END IF;

  -- 停權的賣家什麼都不能做
  IF EXISTS (
    SELECT 1 FROM public.sell_seller_profiles
    WHERE seller_id = NEW.seller_id AND suspended_at IS NOT NULL
  ) THEN
    RAISE EXCEPTION '帳號已被停權，無法上架商品';
  END IF;

  -- 類別必須在白名單內
  SELECT COALESCE(value::jsonb, '[]'::jsonb) INTO v_whitelist
  FROM public.platform_settings WHERE key = 'sell_category_whitelist';

  IF NEW.category IS NULL OR btrim(NEW.category) = '' THEN
    RAISE EXCEPTION '請選擇商品類別';
  END IF;
  IF NOT (NEW.category IN (SELECT jsonb_array_elements_text(COALESCE(v_whitelist, '[]'::jsonb)))) THEN
    RAISE EXCEPTION '這個類別不開放販售';
  END IF;

  IF TG_OP = 'INSERT' THEN
    -- 手機驗證：平台不碰錢，實名是唯一能追到人的手段
    SELECT COALESCE(value, 'true') = 'true' INTO v_need_phone
    FROM public.platform_settings WHERE key = 'sell_require_phone_verified';

    IF COALESCE(v_need_phone, true)
       AND NOT COALESCE((SELECT is_phone_verified FROM public.users WHERE id = NEW.seller_id), false) THEN
      RAISE EXCEPTION '請先完成手機驗證才能上架商品';
    END IF;

    -- 上架則數上限，避免洗版
    SELECT COALESCE(NULLIF(value, '')::int, 20) INTO v_max_active
    FROM public.platform_settings WHERE key = 'sell_max_active_listings';

    SELECT count(*) INTO v_active_cnt
    FROM public.sell_listings
    WHERE seller_id = NEW.seller_id AND status IN ('pending','active');

    IF v_active_cnt >= COALESCE(v_max_active, 20) THEN
      RAISE EXCEPTION '上架數量已達上限（%），請先下架部分商品', COALESCE(v_max_active, 20);
    END IF;

    -- 玩家自己上架一律進待審，審核欄位不給帶
    NEW.status      := 'pending';
    NEW.reviewed_at := NULL;
    NEW.reviewed_by := NULL;
    NEW.review_note := NULL;
    RETURN NEW;
  END IF;

  -- ── 以下是 UPDATE ──

  -- 審核結果不給賣家碰
  NEW.reviewed_at := OLD.reviewed_at;
  NEW.reviewed_by := OLD.reviewed_by;
  NEW.review_note := OLD.review_note;

  -- 狀態只能：自行下架，或把被退回／已下架的重新送審
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF NOT (
      NEW.status = 'removed'
      OR (NEW.status = 'pending' AND OLD.status IN ('rejected','removed'))
    ) THEN
      RAISE EXCEPTION '不能自行變更上架狀態';
    END IF;
  END IF;

  -- 防換餌：上架後改內容要重新送審。
  -- 不擋的話就是「先上架人畜無害的東西、過審後把內容換掉」。
  IF OLD.status IN ('active','sold')
     AND NEW.status = OLD.status
     AND (
          NEW.title    IS DISTINCT FROM OLD.title
       OR NEW.note     IS DISTINCT FROM OLD.note
       OR NEW.price    IS DISTINCT FROM OLD.price
       OR NEW.images   IS DISTINCT FROM OLD.images
       OR NEW.items    IS DISTINCT FROM OLD.items
       OR NEW.category IS DISTINCT FROM OLD.category
     ) THEN
    NEW.status      := 'pending';
    NEW.reviewed_at := NULL;
    NEW.reviewed_by := NULL;
    NEW.review_note := NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sell_guard_listing ON public.sell_listings;
CREATE TRIGGER trg_sell_guard_listing
  BEFORE INSERT OR UPDATE ON public.sell_listings
  FOR EACH ROW EXECUTE FUNCTION public.sell_guard_listing();

-- ============================================================
-- G. 公開瀏覽：待審／退回的不能被看到
-- ============================================================
--
-- 既有政策是 `status = 'active' OR 自己的 OR 買過的`。
-- 'sold' 要留著讓買家還看得到自己買過的那筆；'pending'/'rejected'/'removed' 只有賣家自己看得到。

DROP POLICY IF EXISTS "Sell listings - public read active" ON public.sell_listings;
CREATE POLICY "Sell listings - public read active" ON public.sell_listings
  FOR SELECT USING (
    status IN ('active','sold')
    OR seller_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.sell_orders o
      WHERE o.listing_id = sell_listings.id AND o.buyer_id = auth.uid()
    )
  );

COMMIT;
