-- 619: 回收費率改成後台可調的一張表（老闆 2026-08-25「回收機制大改版」）
--
-- 變更重點：
--   ① 費率從函數裡的 hardcode 搬進 recycle_rates 表，後台「回收價格設定」頁可調
--   ② 基準一律是「單抽價」。不逐品項填實物價值 —— 沒人力，而且 product_prizes.recycle_value
--      這個欄位早就存在卻是 1,778 個品項零填寫，靠人工維護的方案不會被執行
--   ③ 品項層級的「回收設定」(decompose_type/decompose_value) 停用。全站 1,778 個品項
--      本來就全是 auto，沒有一個設過；留著只會讓兩套規則打架
--   ④ 結構依老闆指定：轉蛋、盒玩各一個 %；一番賞／抽卡／自製賞各有「大賞 %」與「小賞 %」
--
-- 大賞判定維持 total <= 3（品項初始總數）。一番賞的 A／B／C 賞平均 2.0–2.5 件，
-- 這個門檻抓得剛好；改用「總量佔比 < 5%」會讓 93% 的序列庫存變大賞（抽卡的 D 賞太多，
-- 害其他品項全部看起來很稀有），已試算否決。

CREATE TABLE IF NOT EXISTS public.recycle_rates (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_type  text        NOT NULL,
  -- all＝該類型不分賞等（轉蛋／盒玩）｜major＝大賞（total <= 3）｜normal＝一般賞
  tier          text        NOT NULL,
  rate_percent  numeric(6,2) NOT NULL,
  -- 下限。低價商品乘完不足 1 時至少給這個數，避免算出 0
  min_value     integer     NOT NULL DEFAULT 1,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  updated_by    text,
  CONSTRAINT recycle_rates_type_check CHECK (product_type IN ('gacha','blindbox','ichiban','card','custom')),
  CONSTRAINT recycle_rates_tier_check CHECK (tier IN ('all','major','normal')),
  CONSTRAINT recycle_rates_pct_check  CHECK (rate_percent >= 0 AND rate_percent <= 100),
  CONSTRAINT recycle_rates_min_check  CHECK (min_value >= 0),
  UNIQUE (product_type, tier)
);

COMMENT ON TABLE  public.recycle_rates IS '回收費率。基準為商品單抽價，後台「商品管理 → 回收價格設定」可調。';
COMMENT ON COLUMN public.recycle_rates.tier IS 'all＝不分賞等（轉蛋/盒玩）｜major＝大賞（品項初始總數 <= 3）｜normal＝一般賞';

-- 初始值：轉蛋／盒玩 15%（現行固定 10 對這兩類太低，盒玩 355 只有 2.8%）；
-- 大賞 20% 沿用現行；一般賞 3%（309 元的一番賞約等於現行的固定 10，行為接近不變）
INSERT INTO public.recycle_rates (product_type, tier, rate_percent, updated_by) VALUES
  ('gacha',    'all',    15, 'migration_619'),
  ('blindbox', 'all',    15, 'migration_619'),
  ('ichiban',  'major',  20, 'migration_619'),
  ('ichiban',  'normal',  3, 'migration_619'),
  ('card',     'major',  20, 'migration_619'),
  ('card',     'normal',  3, 'migration_619'),
  ('custom',   'major',  20, 'migration_619'),
  ('custom',   'normal',  3, 'migration_619')
ON CONFLICT (product_type, tier) DO NOTHING;

-- 前台要讀得到費率（商品頁想顯示「回收可換多少」時用），只給讀
ALTER TABLE public.recycle_rates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS recycle_rates_read ON public.recycle_rates;
CREATE POLICY recycle_rates_read ON public.recycle_rates
  FOR SELECT TO anon, authenticated USING (true);

-- ── 費率查詢：大賞判定也只有這一份 ─────────────────────────
CREATE OR REPLACE FUNCTION public.recycle_rate_for(
  p_product_type text,
  p_prize_total  integer
) RETURNS TABLE (tier text, rate_percent numeric, min_value integer)
LANGUAGE sql STABLE AS $$
  SELECT r.tier, r.rate_percent, r.min_value
  FROM public.recycle_rates r
  WHERE r.product_type = p_product_type
    AND r.tier = CASE
          WHEN p_product_type IN ('gacha','blindbox') THEN 'all'
          -- total 為 NULL 時視為一般賞（與改版前的 IF total <= 3 行為一致）
          WHEN COALESCE(p_prize_total, 999) <= 3      THEN 'major'
          ELSE 'normal'
        END
  LIMIT 1;
$$;

-- ── calc_recycle_value 改讀費率表 ──────────────────────────
-- 舊簽名吃 decompose_type/decompose_value，改版後不再有品項層級設定，
-- 兩個呼叫端（dismantle_prizes、estimate_recycle_value）在本檔一併換掉。
DROP FUNCTION IF EXISTS public.calc_recycle_value(text, numeric, integer, text, integer);

CREATE OR REPLACE FUNCTION public.calc_recycle_value(
  p_product_type text,
  p_price        numeric,
  p_prize_total  integer
) RETURNS integer
LANGUAGE sql STABLE AS $$
  SELECT GREATEST(
           r.min_value,
           FLOOR(COALESCE(p_price, 0) * r.rate_percent / 100)
         )::integer
  FROM public.recycle_rate_for(p_product_type, p_prize_total) r;
$$;

COMMENT ON FUNCTION public.calc_recycle_value IS
  '回收價唯一規則來源，讀 recycle_rates。基準為單抽價。dismantle_prizes（實際入帳）與 estimate_recycle_value（前台預覽）都呼叫它。';

GRANT EXECUTE ON FUNCTION public.calc_recycle_value(text, numeric, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.recycle_rate_for(text, integer) TO authenticated, service_role;

-- ── 前台預覽 RPC ───────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.estimate_recycle_value(p_record_ids bigint[])
RETURNS TABLE (
  draw_record_id bigint,
  recycle_value  integer,
  can_recycle    boolean,
  reason         text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    dr.id,
    public.calc_recycle_value(p.type, p.price, pp.total),
    (dr.status = 'in_warehouse' AND p.sale_mode <> 'lottery'),
    CASE
      WHEN p.sale_mode = 'lottery'     THEN 'lottery'
      WHEN dr.status <> 'in_warehouse' THEN 'not_in_warehouse'
      ELSE NULL
    END
  FROM public.draw_records   dr
  JOIN public.product_prizes pp ON pp.id = dr.product_prize_id
  JOIN public.products       p  ON p.id  = pp.product_id
  WHERE dr.id = ANY(p_record_ids)
    AND dr.user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.estimate_recycle_value(bigint[]) FROM public;
GRANT EXECUTE ON FUNCTION public.estimate_recycle_value(bigint[]) TO authenticated;

-- ── 實際入帳 ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.dismantle_prizes(
  p_record_ids bigint[],
  p_user_id    uuid
) RETURNS TABLE (success_count integer, total_refund integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_record      RECORD;
  v_refund      INTEGER := 0;
  v_count       INTEGER := 0;
  v_prize_value INTEGER;
BEGIN
  FOR v_record IN
    SELECT dr.id, dr.product_prize_id, pp.total, p.price, p.type AS product_type
    FROM   public.draw_records   dr
    JOIN   public.product_prizes pp ON pp.id = dr.product_prize_id
    JOIN   public.products       p  ON p.id  = pp.product_id
    WHERE  dr.id      = ANY(p_record_ids)
      AND  dr.user_id = p_user_id
      AND  dr.status  = 'in_warehouse'
      -- 抽籤販售的中籤品項不可回收：那是 0 元抽來的，
      -- 回收等於沒付一毛錢就換到 G 幣
      AND  p.sale_mode <> 'lottery'
  LOOP
    v_prize_value := public.calc_recycle_value(
      v_record.product_type, v_record.price, v_record.total
    );

    UPDATE public.draw_records
    SET status = 'dismantled', refund_amount = v_prize_value
    WHERE id = v_record.id;

    -- 轉蛋/盒玩：回收後庫存歸還原商品（實體仍在廠商手上，可再次出貨）
    -- 一番賞/抽卡/自製賞為序列商品不加回，避免破壞抽獎順序與種子驗證
    IF v_record.product_type IN ('gacha', 'blindbox') AND v_record.product_prize_id IS NOT NULL THEN
      UPDATE public.product_prizes
      SET remaining = COALESCE(remaining, 0) + 1
      WHERE id = v_record.product_prize_id;
    END IF;

    INSERT INTO public.admin_recycle_pool (
      draw_record_id, user_id, product_id, product_prize_id, prize_name, prize_level, recycle_value
    )
    SELECT v_record.id, p_user_id, pp.product_id, pp.id, pp.name, pp.level, v_prize_value
    FROM   public.product_prizes pp
    WHERE  pp.id = v_record.product_prize_id
    ON CONFLICT DO NOTHING;

    v_refund := v_refund + v_prize_value;
    v_count  := v_count  + 1;
  END LOOP;

  IF v_refund > 0 THEN
    UPDATE public.users
    SET tokens = COALESCE(tokens, 0) + v_refund
    WHERE id = p_user_id;
  END IF;

  RETURN QUERY SELECT v_count, v_refund;
END;
$$;

-- ── 品項層級的回收設定停用 ─────────────────────────────────
-- 欄位不刪（匯入腳本與歷史資料還引用著），但從此不再被任何規則讀取。
COMMENT ON COLUMN public.product_prizes.decompose_type IS
  '⚠️ 已停用（migration 619）。回收費率統一由 recycle_rates 決定，後台品項編輯已移除此欄位。';
COMMENT ON COLUMN public.product_prizes.decompose_value IS
  '⚠️ 已停用（migration 619）。見 decompose_type 說明。';
