-- 621: 廠商設定的完整操作紀錄（老闆 2026-08-25）
--
-- 「正常初始設定完，後續比較少會去編輯」—— 正因為少動，動的那一次才要查得到：
-- 誰、什麼時候、把哪個值從多少改成多少。action_logs 只存得下一包 JSON detail，
-- 要在頁面上列出「這家廠商的設定變更史」很難查；獨立一張表最直接。
--
-- supplier_id 為 NULL 代表改的是全站預設（platform_settings），不是特定廠商。

CREATE TABLE IF NOT EXISTS public.supplier_setting_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id bigint REFERENCES public.suppliers(id) ON DELETE CASCADE,
  field       text        NOT NULL,
  old_value   text,
  new_value   text,
  admin_id    bigint,
  changed_by  text        NOT NULL,
  ip          text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.supplier_setting_logs IS '廠商設定變更史（後台「廠商管理 → 廠商設定」）。supplier_id 為 NULL＝改的是全站預設。';
COMMENT ON COLUMN public.supplier_setting_logs.field IS
  'recycle_settlement_mode｜recycle_margin_supplier_share｜global_recycle_settlement_mode｜global_recycle_margin_supplier_share';

CREATE INDEX IF NOT EXISTS idx_supplier_setting_logs_supplier
  ON public.supplier_setting_logs (supplier_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_setting_logs_time
  ON public.supplier_setting_logs (created_at DESC);

-- 後台走 service role 讀寫，前台完全不該碰
ALTER TABLE public.supplier_setting_logs ENABLE ROW LEVEL SECURITY;
