-- 654_stg_missing_tables.sql
--
-- 補上 STG 缺的兩張表，跟 PROD 對齊。
--
-- ## 怎麼發現的
--
-- 2026-08-31 後台（連 STG）開「會員管理」整頁載不出來：
--   Could not find the table 'public.user_event_logs' in the schema cache
--
-- 順手照 CLAUDE.md 的 diff 指令比了一輪，PROD 有、STG 沒有的共四張：
--
--   user_event_logs   ← 補（後台六處在用：會員最後登入 IP、風控多 IP、綠界 callback、風控處置）
--   meeting_logs      ← 補（後台「會議紀錄」頁與它的 API 在用）
--   capability_gaps   ← **不補**。CLAUDE.md 明列 STG 不需要 GB哥 AI 基礎建設
--   _migration_log    ← **不補**。沒有任何程式碼讀它
--
-- 整份是 IF NOT EXISTS，在 PROD 跑就是 no-op，兩邊都跑不會壞。
--
-- ## RLS
--
-- 兩張都照 PROD：開 RLS 但**不建任何 policy** —— 只有 service_role（後台）會碰它們，
-- 前台完全不該讀得到。這跟「開了 RLS 忘了建 policy」那個坑不同：
-- 那個坑是前台要讀卻讀不到；這裡是刻意不讓前台讀。

BEGIN;

-- ── user_event_logs：玩家事件（登入、風控處置、金流確認）────────────
CREATE TABLE IF NOT EXISTS user_event_logs (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    uuid,
  event_type text NOT NULL,
  detail     jsonb,
  ip         text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_event_logs_user_id    ON user_event_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_user_event_logs_event_type ON user_event_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_user_event_logs_created_at ON user_event_logs (created_at DESC);

ALTER TABLE user_event_logs ENABLE ROW LEVEL SECURITY;

-- ── meeting_logs：後台會議紀錄 ──────────────────────────────────
CREATE TABLE IF NOT EXISTS meeting_logs (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        text NOT NULL,
  meeting_at   timestamptz NOT NULL,
  participants text NOT NULL DEFAULT '',
  content      text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

ALTER TABLE meeting_logs ENABLE ROW LEVEL SECURITY;

COMMIT;
