-- 676: 交易所檢舉（老闆 2026-09-02：詳情頁分享旁加「⋯」→ 下方彈窗檢舉，
-- radio 預設原因、不給填字）。
-- 不共用 sell_reports —— 那張的 listing_id 綁的是商城，FK 對不上。

CREATE TABLE IF NOT EXISTS public.marketplace_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid NOT NULL REFERENCES users(id),
  listing_id bigint NOT NULL REFERENCES marketplace_listings(id),
  seller_id uuid REFERENCES users(id),
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved','dismissed')),
  admin_note text,
  handled_at timestamptz,
  handled_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- 同一個人對同一筆上架只留一筆，重複檢舉就更新原因
  UNIQUE (reporter_id, listing_id)
);

CREATE INDEX IF NOT EXISTS idx_marketplace_reports_status ON public.marketplace_reports (status, created_at DESC);

ALTER TABLE public.marketplace_reports ENABLE ROW LEVEL SECURITY;
-- 檢舉人可以看自己送過什麼；寫入一律走下面的 SECURITY DEFINER RPC
DROP POLICY IF EXISTS "reporter can view own" ON public.marketplace_reports;
CREATE POLICY "reporter can view own" ON public.marketplace_reports
  FOR SELECT USING (auth.uid() = reporter_id);

CREATE OR REPLACE FUNCTION public.report_marketplace_listing(p_listing_id bigint, p_reason text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_lst RECORD;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', '請先登入');
  END IF;
  IF p_reason IS NULL OR length(trim(p_reason)) = 0 OR length(p_reason) > 100 THEN
    RETURN jsonb_build_object('success', false, 'message', '選一個檢舉原因');
  END IF;

  SELECT * INTO v_lst FROM marketplace_listings WHERE id = p_listing_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', '找不到這筆上架');
  END IF;
  IF v_lst.seller_id = v_uid THEN
    RETURN jsonb_build_object('success', false, 'message', '不能檢舉自己的上架');
  END IF;

  INSERT INTO marketplace_reports (reporter_id, listing_id, seller_id, reason)
  VALUES (v_uid, p_listing_id, v_lst.seller_id, trim(p_reason))
  ON CONFLICT (reporter_id, listing_id)
  DO UPDATE SET reason = EXCLUDED.reason, status = 'open', created_at = now();

  RETURN jsonb_build_object('success', true, 'message', '已收到檢舉，平台會盡快查看');
END;
$$;
